"""
RBAC Default Roles and Permissions.

Defines the system-wide roles and permissions available in Aragora.
Organizations can create custom roles based on these templates.

This package re-exports all permissions, roles, and helper functions
for backward compatibility.
"""

from __future__ import annotations

# Re-export all permissions
from .permissions import (  # noqa: F401
    # Debate
    PERM_DEBATE_CREATE,
    PERM_DEBATE_READ,
    PERM_DEBATE_UPDATE,
    PERM_DEBATE_DELETE,
    PERM_DEBATE_RUN,
    PERM_DEBATE_STOP,
    PERM_DEBATE_FORK,
    PERM_SETTLEMENT_READ,
    PERM_SETTLEMENT_WRITE,
    # Agent
    PERM_AGENT_CREATE,
    PERM_AGENT_READ,
    PERM_AGENT_UPDATE,
    PERM_AGENT_DELETE,
    PERM_AGENT_DEPLOY,
    # User
    PERM_USER_READ,
    PERM_USER_INVITE,
    PERM_USER_REMOVE,
    PERM_USER_CHANGE_ROLE,
    PERM_USER_IMPERSONATE,
    # Organization
    PERM_ORG_READ,
    PERM_ORG_UPDATE,
    PERM_ORG_BILLING,
    PERM_ORG_AUDIT,
    PERM_ORG_EXPORT,
    PERM_ORG_INVITE,
    PERM_ORG_DELETE,
    # API
    PERM_API_GENERATE_KEY,
    PERM_API_REVOKE_KEY,
    # Memory
    PERM_MEMORY_READ,
    PERM_MEMORY_UPDATE,
    PERM_MEMORY_DELETE,
    # Workflow
    PERM_WORKFLOW_CREATE,
    PERM_WORKFLOW_READ,
    PERM_WORKFLOW_RUN,
    PERM_WORKFLOW_DELETE,
    # Analytics
    PERM_ANALYTICS_READ,
    PERM_ANALYTICS_EXPORT,
    PERM_PERFORMANCE_READ,
    PERM_PERFORMANCE_WRITE,
    PERM_ANALYTICS_CONFIGURE,
    PERM_ANALYTICS_QUERY,
    # Cross-pollination
    PERM_CROSS_POLLINATION_READ,
    PERM_CROSS_POLLINATION_WRITE,
    # Introspection & History
    PERM_INTROSPECTION_READ,
    PERM_HISTORY_READ,
    # Reasoning
    PERM_REASONING_READ,
    PERM_REASONING_UPDATE,
    # Knowledge
    PERM_KNOWLEDGE_READ,
    PERM_KNOWLEDGE_WRITE,
    PERM_KNOWLEDGE_UPDATE,
    PERM_KNOWLEDGE_DELETE,
    PERM_KNOWLEDGE_SHARE,
    PERM_KNOWLEDGE_ADMIN,
    PERM_CULTURE_READ,
    PERM_CULTURE_WRITE,
    # Provenance
    PERM_PROVENANCE_READ,
    PERM_PROVENANCE_VERIFY,
    PERM_PROVENANCE_EXPORT,
    # Inbox
    PERM_INBOX_READ,
    PERM_INBOX_UPDATE,
    # Skills
    PERM_SKILLS_READ,
    PERM_SKILLS_INSTALL,
    PERM_SKILLS_PUBLISH,
    PERM_SKILLS_RATE,
    # Training & Evidence
    PERM_TRAINING_READ,
    PERM_TRAINING_CREATE,
    PERM_EVIDENCE_READ,
    PERM_EVIDENCE_CREATE,
    PERM_EVIDENCE_DELETE,
    # Documents
    PERM_DOCUMENTS_READ,
    PERM_DOCUMENTS_CREATE,
    PERM_UPLOAD_CREATE,
    PERM_SPEECH_CREATE,
    # Connectors
    PERM_CONNECTOR_READ,
    PERM_CONNECTOR_CREATE,
    PERM_CONNECTOR_DELETE,
    PERM_CONNECTOR_AUTHORIZE,
    PERM_CONNECTOR_ROTATE,
    PERM_CONNECTOR_TEST,
    PERM_CONNECTOR_UPDATE,
    PERM_CONNECTOR_ROLLBACK,
    PERM_CONNECTOR_CONFIGURE,
    # Bot & Feedback
    PERM_BOTS_READ,
    PERM_FEEDBACK_READ,
    PERM_FEEDBACK_WRITE,
    PERM_FEEDBACK_ALL,
    # Device
    PERM_DEVICE_READ,
    PERM_DEVICE_WRITE,
    PERM_DEVICE_NOTIFY,
    # Repository
    PERM_REPOSITORY_READ,
    PERM_REPOSITORY_CREATE,
    PERM_REPOSITORY_UPDATE,
    PERM_REPOSITORY_DELETE,
    # Bindings
    PERM_BINDINGS_READ,
    PERM_BINDINGS_CREATE,
    PERM_BINDINGS_UPDATE,
    PERM_BINDINGS_DELETE,
    # Admin
    PERM_ADMIN_CONFIG,
    PERM_ADMIN_METRICS,
    PERM_ADMIN_FEATURES,
    PERM_ADMIN_ALL,
    PERM_ADMIN_AUDIT,
    PERM_ADMIN_SECURITY,
    PERM_ADMIN_SYSTEM,
    # Webhook
    PERM_WEBHOOK_READ,
    PERM_WEBHOOK_CREATE,
    PERM_WEBHOOK_DELETE,
    PERM_WEBHOOK_ADMIN,
    # Checkpoint & Replay
    PERM_CHECKPOINT_READ,
    PERM_CHECKPOINT_CREATE,
    PERM_CHECKPOINT_DELETE,
    PERM_REPLAYS_READ,
    # Gauntlet
    PERM_GAUNTLET_RUN,
    PERM_GAUNTLET_READ,
    PERM_GAUNTLET_DELETE,
    PERM_GAUNTLET_SIGN,
    PERM_GAUNTLET_COMPARE,
    PERM_GAUNTLET_EXPORT,
    # Marketplace
    PERM_MARKETPLACE_READ,
    PERM_MARKETPLACE_PUBLISH,
    PERM_MARKETPLACE_IMPORT,
    PERM_MARKETPLACE_RATE,
    PERM_MARKETPLACE_REVIEW,
    PERM_MARKETPLACE_DELETE,
    # Explainability
    PERM_EXPLAINABILITY_READ,
    PERM_EXPLAINABILITY_BATCH,
    # Findings
    PERM_FINDINGS_READ,
    PERM_FINDINGS_UPDATE,
    PERM_FINDINGS_ASSIGN,
    PERM_FINDINGS_BULK,
    # Decision
    PERM_DECISION_CREATE,
    PERM_DECISION_READ,
    PERM_DECISION_UPDATE,
    # Policy
    PERM_POLICY_READ,
    PERM_POLICY_CREATE,
    PERM_POLICY_UPDATE,
    PERM_POLICY_DELETE,
    # Compliance
    PERM_COMPLIANCE_READ,
    PERM_COMPLIANCE_UPDATE,
    PERM_COMPLIANCE_CHECK,
    PERM_COMPLIANCE_GDPR,
    PERM_COMPLIANCE_SOC2,
    PERM_COMPLIANCE_LEGAL,
    PERM_COMPLIANCE_AUDIT,
    # Control Plane
    PERM_CONTROL_PLANE_READ,
    PERM_CONTROL_PLANE_SUBMIT,
    PERM_CONTROL_PLANE_CANCEL,
    PERM_CONTROL_PLANE_DELIBERATE,
    PERM_CONTROL_PLANE_AGENTS,
    PERM_CONTROL_PLANE_AGENTS_READ,
    PERM_CONTROL_PLANE_AGENTS_REGISTER,
    PERM_CONTROL_PLANE_AGENTS_UNREGISTER,
    PERM_CONTROL_PLANE_TASKS,
    PERM_CONTROL_PLANE_TASKS_READ,
    PERM_CONTROL_PLANE_TASKS_SUBMIT,
    PERM_CONTROL_PLANE_TASKS_CLAIM,
    PERM_CONTROL_PLANE_TASKS_COMPLETE,
    PERM_CONTROL_PLANE_HEALTH_READ,
    # Finance
    PERM_FINANCE_READ,
    PERM_FINANCE_WRITE,
    PERM_FINANCE_APPROVE,
    # Receipt
    PERM_RECEIPT_READ,
    PERM_RECEIPT_VERIFY,
    PERM_RECEIPT_EXPORT,
    PERM_RECEIPT_SEND,
    # Scheduler
    PERM_SCHEDULER_READ,
    PERM_SCHEDULER_CREATE,
    PERM_SCHEDULER_EXECUTE,
    # Cost
    PERM_COST_READ,
    PERM_COST_WRITE,
    # Queue
    PERM_QUEUE_READ,
    PERM_QUEUE_MANAGE,
    PERM_QUEUE_ADMIN,
    # Nomic
    PERM_NOMIC_READ,
    PERM_NOMIC_ADMIN,
    # Orchestration
    PERM_ORCHESTRATION_READ,
    PERM_ORCHESTRATION_EXECUTE,
    # System
    PERM_SYSTEM_HEALTH_READ,
    # Verticals
    PERM_VERTICALS_READ,
    PERM_VERTICALS_WRITE,
    # Canvas
    PERM_CANVAS_READ,
    PERM_CANVAS_CREATE,
    PERM_CANVAS_UPDATE,
    PERM_CANVAS_DELETE,
    PERM_CANVAS_RUN,
    # Verification
    PERM_VERIFICATION_READ,
    PERM_VERIFICATION_CREATE,
    # Codebase
    PERM_CODEBASE_READ,
    PERM_CODEBASE_ANALYZE,
    # Data Governance
    PERM_DATA_CLASSIFICATION_READ,
    PERM_DATA_CLASSIFICATION_CLASSIFY,
    PERM_DATA_CLASSIFICATION_UPDATE,
    PERM_DATA_RETENTION_READ,
    PERM_DATA_RETENTION_UPDATE,
    PERM_DATA_LINEAGE_READ,
    PERM_PII_READ,
    PERM_PII_REDACT,
    PERM_PII_MASK,
    # Computer-Use
    PERM_COMPUTER_USE_READ,
    PERM_COMPUTER_USE_EXECUTE,
    PERM_COMPUTER_USE_BROWSER,
    PERM_COMPUTER_USE_SHELL,
    PERM_COMPUTER_USE_FILE_READ,
    PERM_COMPUTER_USE_FILE_WRITE,
    PERM_COMPUTER_USE_SCREENSHOT,
    PERM_COMPUTER_USE_NETWORK,
    PERM_COMPUTER_USE_ADMIN,
    # Compliance Policy
    PERM_COMPLIANCE_POLICY_READ,
    PERM_COMPLIANCE_POLICY_UPDATE,
    PERM_COMPLIANCE_POLICY_ENFORCE,
    # Audit Log
    PERM_AUDIT_LOG_READ,
    PERM_AUDIT_LOG_EXPORT,
    PERM_AUDIT_LOG_SEARCH,
    PERM_AUDIT_LOG_STREAM,
    PERM_AUDIT_LOG_CONFIGURE,
    PERM_AUDIT_LOG_DELETE,
    # Vendor
    PERM_VENDOR_READ,
    PERM_VENDOR_APPROVE,
    # Team
    PERM_TEAM_CREATE,
    PERM_TEAM_READ,
    PERM_TEAM_UPDATE,
    PERM_TEAM_DELETE,
    PERM_TEAM_ADD_MEMBER,
    PERM_TEAM_REMOVE_MEMBER,
    PERM_TEAM_SHARE,
    PERM_TEAM_DISSOLVE,
    # Workspace
    PERM_WORKSPACE_CREATE,
    PERM_WORKSPACE_READ,
    PERM_WORKSPACE_UPDATE,
    PERM_WORKSPACE_DELETE,
    PERM_WORKSPACE_MEMBER_ADD,
    PERM_WORKSPACE_MEMBER_REMOVE,
    PERM_WORKSPACE_MEMBER_CHANGE_ROLE,
    PERM_WORKSPACE_SHARE,
    # Quota & Budget
    PERM_QUOTA_READ,
    PERM_QUOTA_UPDATE,
    PERM_QUOTA_OVERRIDE,
    PERM_COST_CENTER_READ,
    PERM_COST_CENTER_UPDATE,
    PERM_BUDGET_READ,
    PERM_BUDGET_UPDATE,
    PERM_BUDGET_OVERRIDE,
    # Billing
    PERM_BILLING_READ,
    PERM_BILLING_RECOMMENDATIONS_READ,
    PERM_BILLING_RECOMMENDATIONS_APPLY,
    PERM_BILLING_FORECAST_READ,
    PERM_BILLING_FORECAST_SIMULATE,
    PERM_BILLING_EXPORT_HISTORY,
    # Session & Auth
    PERM_SESSION_READ,
    PERM_SESSION_REVOKE,
    PERM_SESSION_CREATE,
    PERM_AUTH_RESET_PASSWORD,
    PERM_AUTH_REQUIRE_MFA,
    PERM_AUTH_READ,
    PERM_AUTH_CREATE,
    PERM_AUTH_UPDATE,
    PERM_AUTH_REVOKE,
    PERM_API_KEY_CREATE,
    PERM_API_KEY_REVOKE,
    PERM_API_KEY_LIST_ALL,
    PERM_API_KEY_EXPORT_SECRET,
    # Approval
    PERM_APPROVAL_REQUEST,
    PERM_APPROVAL_GRANT,
    PERM_APPROVAL_READ,
    # Template
    PERM_TEMPLATE_CREATE,
    PERM_TEMPLATE_READ,
    PERM_TEMPLATE_UPDATE,
    PERM_TEMPLATE_DELETE,
    # Role
    PERM_ROLE_CREATE,
    PERM_ROLE_READ,
    PERM_ROLE_UPDATE,
    PERM_ROLE_DELETE,
    # Backup & DR
    PERM_BACKUP_CREATE,
    PERM_BACKUP_READ,
    PERM_BACKUP_RESTORE,
    PERM_BACKUP_DELETE,
    PERM_DR_READ,
    PERM_DR_EXECUTE,
    # Gateway (OpenClaw)
    PERM_GATEWAY_EXECUTE,
    PERM_GATEWAY_READ,
    PERM_GATEWAY_CONFIGURE,
    PERM_GATEWAY_DEVICE_REGISTER,
    PERM_GATEWAY_DEVICE_UNREGISTER,
    PERM_GATEWAY_PLUGIN_INSTALL,
    PERM_GATEWAY_PLUGIN_UNINSTALL,
    PERM_GATEWAY_ADMIN,
    # Gateway - Secure Gateway
    PERM_GATEWAY_AGENT_CREATE,
    PERM_GATEWAY_AGENT_READ,
    PERM_GATEWAY_AGENT_DELETE,
    PERM_GATEWAY_CREDENTIAL_CREATE,
    PERM_GATEWAY_CREDENTIAL_READ,
    PERM_GATEWAY_CREDENTIAL_DELETE,
    PERM_GATEWAY_CREDENTIAL_ROTATE,
    PERM_GATEWAY_HYBRID_DEBATE,
    PERM_GATEWAY_HEALTH,
    # Route permissions (middleware-referenced resources)
    PERM_AUDITING_READ,
    PERM_AUDITING_CREATE,
    PERM_BELIEF_READ,
    PERM_BELIEF_WRITE,
    PERM_BILLING_WRITE,
    PERM_CONNECTOR_CREATE_ALIAS,
    PERM_CONNECTOR_DELETE_ALIAS,
    PERM_CONSENSUS_READ,
    PERM_CONSENSUS_CREATE,
    PERM_DOCUMENTS_WRITE,
    PERM_EVOLUTION_WRITE,
    PERM_GALLERY_READ,
    PERM_GALLERY_WRITE,
    PERM_GENESIS_READ,
    PERM_GENESIS_CREATE,
    PERM_INSIGHTS_READ,
    PERM_LABORATORY_READ,
    PERM_LABORATORY_WRITE,
    PERM_LEARNING_READ,
    PERM_LEARNING_WRITE,
    PERM_MOMENTS_READ,
    PERM_MOMENTS_WRITE,
    PERM_PERSONAS_READ,
    PERM_PERSONAS_WRITE,
    PERM_PLUGINS_READ,
    PERM_PODCAST_READ,
    PERM_PODCAST_CREATE,
    PERM_PULSE_WRITE,
    PERM_RELATIONSHIPS_READ,
    PERM_RELATIONSHIPS_WRITE,
    PERM_REPLAYS_CREATE,
    PERM_TOURNAMENTS_READ,
    PERM_TOURNAMENTS_CREATE,
)

# Re-export SYSTEM_PERMISSIONS
from .registry import SYSTEM_PERMISSIONS

# Re-export roles
from .roles import (
    ROLE_OWNER,
    ROLE_ADMIN,
    ROLE_COMPLIANCE_OFFICER,
    ROLE_DEBATE_CREATOR,
    ROLE_TEAM_LEAD,
    ROLE_ANALYST,
    ROLE_VIEWER,
    ROLE_MEMBER,
    SYSTEM_ROLES,
    ROLE_HIERARCHY,
)

# Re-export helpers
from .helpers import (
    get_permission,
    get_role,
    get_role_permissions,
    create_custom_role,
    ROLE_TEMPLATES,
)

__all__ = [
    # Permissions (partial list - all PERM_* are exported)
    "SYSTEM_PERMISSIONS",
    # Roles
    "ROLE_OWNER",
    "ROLE_ADMIN",
    "ROLE_COMPLIANCE_OFFICER",
    "ROLE_DEBATE_CREATOR",
    "ROLE_TEAM_LEAD",
    "ROLE_ANALYST",
    "ROLE_VIEWER",
    "ROLE_MEMBER",
    "SYSTEM_ROLES",
    "ROLE_HIERARCHY",
    # Helpers
    "get_permission",
    "get_role",
    "get_role_permissions",
    "create_custom_role",
    "ROLE_TEMPLATES",
]
