"""
Tests for Gauntlet API Export Utilities.

Tests multi-format export for receipts and heatmaps:
- JSON export
- Markdown export
- HTML export
- CSV export
- SARIF export (security findings)
"""

import json
import subprocess
import sys
import pytest
from datetime import datetime
from pathlib import Path
from unittest.mock import MagicMock

from aragora.gauntlet.api.export import (
    ReceiptExportFormat,
    HeatmapExportFormat,
    ExportOptions,
    export_receipt,
    export_heatmap,
    export_receipts_bundle,
    stream_receipt_json,
    is_pdf_export_available,
    export_receipt_pdf_to_file,
)


# ============================================================================
# Fixtures
# ============================================================================


@pytest.fixture
def sample_receipt():
    """Create a sample DecisionReceipt for testing."""
    receipt = MagicMock()
    receipt.id = "receipt_001"
    receipt.request_id = "req_001"
    receipt.question = "Should we implement rate limiting?"
    receipt.decision = "Yes, implement token bucket rate limiting"
    receipt.confidence = 0.87
    receipt.timestamp = "2024-01-15T10:30:00"
    receipt.debate_duration_seconds = 45.5
    receipt.consensus_reached = True
    receipt.participating_agents = ["claude", "gpt4", "gemini"]
    receipt.agreeing_agents = ["claude", "gpt4"]
    receipt.dissenting_agents = ["gemini"]
    receipt.key_arguments = [
        "Token bucket allows burst handling",
        "Better than fixed window for APIs",
    ]
    receipt.dissenting_views = [
        "Sliding window provides more accuracy",
    ]
    receipt.evidence_cited = ["RFC 6585", "API Best Practices Guide"]
    receipt.risk_flags = []
    receipt.metadata = {"domain": "engineering", "priority": "high"}

    # Mock to_dict method
    receipt.to_dict = MagicMock(
        return_value={
            "id": receipt.id,
            "request_id": receipt.request_id,
            "question": receipt.question,
            "decision": receipt.decision,
            "confidence": receipt.confidence,
            "timestamp": receipt.timestamp,
            "debate_duration_seconds": receipt.debate_duration_seconds,
            "consensus_reached": receipt.consensus_reached,
            "participating_agents": receipt.participating_agents,
            "agreeing_agents": receipt.agreeing_agents,
            "dissenting_agents": receipt.dissenting_agents,
            "key_arguments": receipt.key_arguments,
            "dissenting_views": receipt.dissenting_views,
            "evidence_cited": receipt.evidence_cited,
            "risk_flags": receipt.risk_flags,
            "metadata": receipt.metadata,
        }
    )

    # Mock to_markdown method
    receipt.to_markdown = MagicMock(
        return_value="""# Decision Receipt

**Receipt ID:** `receipt_001`
**Request ID:** `req_001`
**Generated:** 2024-01-15T10:30:00

---

## Question

Should we implement rate limiting?

## Decision

Yes, implement token bucket rate limiting

**Confidence:** 87.0%
**Consensus Reached:** Yes

---

## Participating Agents

- claude (agreed)
- gpt4 (agreed)
- gemini (dissented)

---

## Key Arguments

- Token bucket allows burst handling
- Better than fixed window for APIs

## Dissenting Views

- Sliding window provides more accuracy

---

*Generated by Aragora Gauntlet*
"""
    )

    # Mock to_html method
    html_content = """<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Decision Receipt - receipt_001</title>
</head>
<body>
    <h1>Decision Receipt</h1>
    <p><strong>Receipt ID:</strong> <code>receipt_001</code></p>
    <p><strong>Request ID:</strong> <code>req_001</code></p>
    <div class="decision">
        <h2>Question</h2>
        <p>Should we implement rate limiting?</p>
        <h2>Decision</h2>
        <p>Yes, implement token bucket rate limiting</p>
        <p><strong>Confidence:</strong> 87%</p>
    </div>
    <table>
        <tr><th>Agent</th><th>Position</th></tr>
        <tr><td>claude</td><td>Agreed</td></tr>
        <tr><td>gpt4</td><td>Agreed</td></tr>
        <tr><td>gemini</td><td>Dissented</td></tr>
    </table>
</body>
</html>
"""
    receipt.to_html = MagicMock(return_value=html_content)
    # Mock to_html_paginated for paginated PDF export
    receipt.to_html_paginated = MagicMock(return_value=html_content)

    # Mock to_json method
    receipt.to_json = MagicMock(
        return_value=json.dumps(
            {
                "id": receipt.id,
                "request_id": receipt.request_id,
                "question": receipt.question,
                "decision": receipt.decision,
                "confidence": receipt.confidence,
            }
        )
    )

    # Mock receipt fields needed by CSV/SARIF exports
    receipt.receipt_id = receipt.id
    receipt.gauntlet_id = "gauntlet_001"
    receipt.verdict = "PASS"
    receipt.robustness_score = 0.92
    receipt.vulnerabilities_found = 2
    receipt.vulnerability_details = [
        {
            "id": "vuln_001",
            "severity": "medium",
            "severity_level": "MEDIUM",
            "category": "rate_limiting",
            "title": "Rate limit bypass via header manipulation",
            "description": "Potential bypass of rate limiting through header manipulation",
            "mitigation": "Validate headers server-side",
            "verified": True,
        },
        {
            "id": "vuln_002",
            "severity": "low",
            "severity_level": "LOW",
            "category": "api_design",
            "title": "Missing retry-after header",
            "description": "API does not return retry-after header on rate limit",
            "mitigation": "Add retry-after header to 429 responses",
            "verified": False,
        },
    ]

    return receipt


@pytest.fixture
def sample_heatmap():
    """Create a sample RiskHeatmap for testing."""
    heatmap = MagicMock()
    heatmap.id = "heatmap_001"
    heatmap.gauntlet_id = "gauntlet_001"
    heatmap.generated_at = "2024-01-15T11:00:00"
    heatmap.rows = ["Security", "Performance", "Reliability"]
    heatmap.columns = ["Low", "Medium", "High"]
    heatmap.cells = [
        [0.1, 0.2, 0.1],
        [0.3, 0.4, 0.2],
        [0.2, 0.3, 0.1],
    ]
    heatmap.metadata = {"analysis_type": "risk_assessment"}

    # Properties for CSV and HTML exports
    heatmap.severities = ["low", "medium", "high", "critical"]
    heatmap.categories = ["Security", "Performance", "Reliability"]
    heatmap.total_findings = 12
    heatmap.highest_risk_category = "Performance"
    heatmap.highest_risk_severity = "medium"

    # Mock get_cell to return cell data
    def mock_get_cell(category, severity):
        cell = MagicMock()
        # Return different counts based on category/severity
        counts = {
            ("Security", "low"): 1,
            ("Security", "medium"): 2,
            ("Security", "high"): 1,
            ("Security", "critical"): 0,
            ("Performance", "low"): 3,
            ("Performance", "medium"): 4,
            ("Performance", "high"): 2,
            ("Performance", "critical"): 0,
            ("Reliability", "low"): 2,
            ("Reliability", "medium"): 3,
            ("Reliability", "high"): 1,
            ("Reliability", "critical"): 0,
        }
        cell.count = counts.get((category, severity), 0)
        return cell

    heatmap.get_cell = mock_get_cell

    # Mock get_severity_total
    def mock_severity_total(severity):
        totals = {"low": 6, "medium": 9, "high": 4, "critical": 0}
        return totals.get(severity, 0)

    heatmap.get_severity_total = mock_severity_total

    heatmap.to_dict = MagicMock(
        return_value={
            "id": heatmap.id,
            "gauntlet_id": heatmap.gauntlet_id,
            "generated_at": heatmap.generated_at,
            "rows": heatmap.rows,
            "columns": heatmap.columns,
            "cells": heatmap.cells,
            "metadata": heatmap.metadata,
        }
    )

    # Mock to_svg
    heatmap.to_svg = MagicMock(
        return_value="""<svg width="400" height="300" xmlns="http://www.w3.org/2000/svg">
    <rect x="0" y="0" width="400" height="300" fill="#f8f9fa"/>
    <text x="200" y="30" text-anchor="middle">Risk Heatmap</text>
    <rect x="50" y="50" width="80" height="60" fill="#ffc107"/>
    <text x="90" y="85">Security</text>
</svg>"""
    )

    # Mock to_ascii
    heatmap.to_ascii = MagicMock(
        return_value="""
+-------------+-----+--------+------+----------+
| Category    | Low | Medium | High | Critical |
+-------------+-----+--------+------+----------+
| Security    |   1 |      2 |    1 |        0 |
| Performance |   3 |      4 |    2 |        0 |
| Reliability |   2 |      3 |    1 |        0 |
+-------------+-----+--------+------+----------+
"""
    )

    return heatmap


@pytest.fixture
def export_options():
    """Create default export options."""
    return ExportOptions()


# ============================================================================
# ReceiptExportFormat Tests
# ============================================================================


class TestReceiptExportFormat:
    """Tests for ReceiptExportFormat enum."""

    def test_format_values(self):
        """Test all format values exist."""
        assert ReceiptExportFormat.JSON.value == "json"
        assert ReceiptExportFormat.MARKDOWN.value == "markdown"
        assert ReceiptExportFormat.HTML.value == "html"
        assert ReceiptExportFormat.CSV.value == "csv"
        assert ReceiptExportFormat.SARIF.value == "sarif"
        assert ReceiptExportFormat.PDF.value == "pdf"

    def test_format_from_string(self):
        """Test creating format from string."""
        assert ReceiptExportFormat("json") == ReceiptExportFormat.JSON
        assert ReceiptExportFormat("markdown") == ReceiptExportFormat.MARKDOWN
        assert ReceiptExportFormat("pdf") == ReceiptExportFormat.PDF


class TestHeatmapExportFormat:
    """Tests for HeatmapExportFormat enum."""

    def test_format_values(self):
        """Test all format values exist."""
        assert HeatmapExportFormat.JSON.value == "json"
        assert HeatmapExportFormat.CSV.value == "csv"
        assert HeatmapExportFormat.HTML.value == "html"


# ============================================================================
# ExportOptions Tests
# ============================================================================


class TestExportOptions:
    """Tests for ExportOptions dataclass."""

    def test_default_options(self):
        """Test default export options."""
        options = ExportOptions()

        assert options.include_export_metadata is True
        assert options.include_provenance is True
        assert options.include_config is False
        assert options.validate_schema is False
        assert options.indent == 2
        assert options.sort_keys is False

    def test_custom_options(self):
        """Test custom export options."""
        options = ExportOptions(
            include_export_metadata=False,
            include_provenance=False,
            sort_keys=True,
            indent=4,
        )

        assert options.include_export_metadata is False
        assert options.include_provenance is False
        assert options.sort_keys is True
        assert options.indent == 4


# ============================================================================
# JSON Export Tests
# ============================================================================


class TestJSONExport:
    """Tests for JSON export functionality."""

    def test_export_receipt_json(self, sample_receipt, export_options):
        """Test exporting receipt to JSON."""
        result = export_receipt(
            sample_receipt,
            format=ReceiptExportFormat.JSON,
            options=export_options,
        )

        # Should be valid JSON
        parsed = json.loads(result)
        assert parsed["id"] == "receipt_001"
        assert parsed["decision"] == "Yes, implement token bucket rate limiting"

    def test_export_receipt_json_pretty(self, sample_receipt):
        """Test pretty-printed JSON export."""
        options = ExportOptions(indent=2)
        result = export_receipt(
            sample_receipt,
            format=ReceiptExportFormat.JSON,
            options=options,
        )

        # Should have indentation
        assert "\n" in result
        assert "  " in result

    def test_export_receipt_json_compact(self, sample_receipt):
        """Test compact JSON export with minimal indent."""
        options = ExportOptions(indent=0)
        result = export_receipt(
            sample_receipt,
            format=ReceiptExportFormat.JSON,
            options=options,
        )

        # Should be valid JSON
        parsed = json.loads(result)
        assert parsed["id"] == "receipt_001"
        # With indent=0, indentation should be minimal (0 spaces per level)
        # The output may still have newlines but no leading spaces
        assert "    " not in result  # No 4-space indentation

    def test_export_heatmap_json(self, sample_heatmap, export_options):
        """Test exporting heatmap to JSON."""
        result = export_heatmap(
            sample_heatmap,
            format=HeatmapExportFormat.JSON,
            options=export_options,
        )

        parsed = json.loads(result)
        assert parsed["id"] == "heatmap_001"
        assert len(parsed["rows"]) == 3


# ============================================================================
# Markdown Export Tests
# ============================================================================


class TestMarkdownExport:
    """Tests for Markdown export functionality."""

    def test_export_receipt_markdown(self, sample_receipt, export_options):
        """Test exporting receipt to Markdown."""
        result = export_receipt(
            sample_receipt,
            format=ReceiptExportFormat.MARKDOWN,
            options=export_options,
        )

        # Should contain Markdown headers
        assert "# Decision Receipt" in result or "##" in result
        assert "receipt_001" in result
        assert "rate limiting" in result.lower()

    def test_markdown_includes_decision(self, sample_receipt, export_options):
        """Test Markdown includes decision text."""
        result = export_receipt(
            sample_receipt,
            format=ReceiptExportFormat.MARKDOWN,
            options=export_options,
        )

        assert "token bucket" in result.lower()

    def test_markdown_includes_confidence(self, sample_receipt, export_options):
        """Test Markdown includes confidence score."""
        result = export_receipt(
            sample_receipt,
            format=ReceiptExportFormat.MARKDOWN,
            options=export_options,
        )

        assert "87" in result or "0.87" in result


# ============================================================================
# HTML Export Tests
# ============================================================================


class TestHTMLExport:
    """Tests for HTML export functionality."""

    def test_export_receipt_html(self, sample_receipt, export_options):
        """Test exporting receipt to HTML."""
        result = export_receipt(
            sample_receipt,
            format=ReceiptExportFormat.HTML,
            options=export_options,
        )

        # Should be valid HTML structure
        assert "<" in result
        assert ">" in result
        # Should contain receipt data
        assert "receipt_001" in result

    def test_html_has_structure(self, sample_receipt, export_options):
        """Test HTML has proper structure."""
        result = export_receipt(
            sample_receipt,
            format=ReceiptExportFormat.HTML,
            options=export_options,
        )

        # Should have some HTML elements
        assert "<div" in result or "<p" in result or "<span" in result or "<table" in result

    def test_export_heatmap_html(self, sample_heatmap, export_options):
        """Test exporting heatmap to HTML."""
        result = export_heatmap(
            sample_heatmap,
            format=HeatmapExportFormat.HTML,
            options=export_options,
        )

        assert "<" in result
        # Heatmap should have table or grid structure
        assert "Security" in result or "heatmap" in result.lower()


# ============================================================================
# CSV Export Tests
# ============================================================================


class TestCSVExport:
    """Tests for CSV export functionality."""

    def test_export_receipt_csv(self, sample_receipt, export_options):
        """Test exporting receipt to CSV."""
        result = export_receipt(
            sample_receipt,
            format=ReceiptExportFormat.CSV,
            options=export_options,
        )

        # Should have comma-separated values
        assert "," in result
        # Should have header row
        lines = result.strip().split("\n")
        assert len(lines) >= 1

    def test_export_heatmap_csv(self, sample_heatmap, export_options):
        """Test exporting heatmap to CSV."""
        result = export_heatmap(
            sample_heatmap,
            format=HeatmapExportFormat.CSV,
            options=export_options,
        )

        assert "," in result
        # Should have rows
        lines = result.strip().split("\n")
        assert len(lines) >= 1


# ============================================================================
# SARIF Export Tests
# ============================================================================


class TestSARIFExport:
    """Tests for SARIF export functionality."""

    def test_export_receipt_sarif(self, sample_receipt, export_options):
        """Test exporting receipt to SARIF format."""
        result = export_receipt(
            sample_receipt,
            format=ReceiptExportFormat.SARIF,
            options=export_options,
        )

        # Should be valid JSON
        parsed = json.loads(result)

        # SARIF structure
        assert "$schema" in parsed or "version" in parsed
        assert "runs" in parsed

    def test_sarif_has_tool_info(self, sample_receipt, export_options):
        """Test SARIF includes tool information."""
        result = export_receipt(
            sample_receipt,
            format=ReceiptExportFormat.SARIF,
            options=export_options,
        )

        parsed = json.loads(result)

        # Should have tool info in runs
        if parsed.get("runs"):
            run = parsed["runs"][0]
            assert "tool" in run


# ============================================================================
# PDF Export Tests
# ============================================================================

# Real WeasyPrint renders run in a child interpreter, never in the pytest
# process. WeasyPrint 68's FontConfiguration.__init__ calls FcConfigDestroy() on
# its FcConfig and also leaves an ffi.gc(FcConfigDestroy) destructor attached, so
# garbage-collecting one frees the config pango still holds and
# pango_fc_font_map_finalize() then writes to freed memory. In a shared test
# process that corrupted unrelated CPython allocations later on: a dataclass
# ``__init__`` compiled without its ``_dflt_metadata`` cell ("NameError: cannot
# access free variable" in tests/server/handlers) or a segfault in dataclasses.
# The child drops the redundant destructor so its own render cannot crash.
_REPO_ROOT = Path(__file__).resolve().parents[3]
_PDF_CHILD = """
import sys, types
import weasyprint.text.fonts as fonts
_init = fonts.FontConfiguration.__init__
def _init_without_double_release(self):
    _init(self)
    fonts.ffi.gc(self._config, None)
fonts.FontConfiguration.__init__ = _init_without_double_release
from aragora.gauntlet.api.export import (
    ExportOptions, ReceiptExportFormat, export_receipt, export_receipt_pdf_to_file,
)
html = sys.stdin.read()
receipt = types.SimpleNamespace(to_html=lambda **_: html, to_html_paginated=lambda **_: html)
if len(sys.argv) > 1:
    print(export_receipt_pdf_to_file(receipt, sys.argv[1], options=ExportOptions()), end="")
else:
    sys.stdout.buffer.write(
        export_receipt(receipt, format=ReceiptExportFormat.PDF, options=ExportOptions())
    )
"""


def _render_pdf_in_child(receipt, *args: str) -> subprocess.CompletedProcess:
    """Render ``receipt``'s HTML to PDF with real WeasyPrint in a child interpreter."""
    proc = subprocess.run(
        [sys.executable, "-c", _PDF_CHILD, *args],
        input=receipt.to_html_paginated().encode(),
        capture_output=True,
        cwd=_REPO_ROOT,
        timeout=120,
    )
    assert proc.returncode == 0, proc.stderr.decode(errors="replace")
    return proc


@pytest.fixture(autouse=True)
def _no_in_process_weasyprint_render(monkeypatch):
    """Fail any test in this module that renders a real PDF in the pytest process."""
    try:
        import weasyprint
    except (ImportError, OSError):
        return

    def _refuse(*_args, **_kwargs):
        raise AssertionError("render real PDFs with _render_pdf_in_child, not in-process")

    monkeypatch.setattr(weasyprint.HTML, "write_pdf", _refuse)


class TestPDFExport:
    """Tests for PDF export functionality."""

    def test_is_pdf_export_available(self):
        """Test PDF export availability check."""
        # This should return a boolean without error
        result = is_pdf_export_available()
        assert isinstance(result, bool)

    def test_export_receipt_pdf_returns_bytes(self, sample_receipt):
        """Test exporting receipt to PDF returns bytes."""
        if not is_pdf_export_available():
            pytest.skip("WeasyPrint native dependencies unavailable")

        result = _render_pdf_in_child(sample_receipt).stdout

        # Should be bytes (PDF content)
        assert isinstance(result, bytes)
        # PDF files start with %PDF
        assert result[:4] == b"%PDF"

    def test_export_receipt_pdf_with_mock(self, sample_receipt, export_options, monkeypatch):
        """Test PDF export with mocked WeasyPrint."""
        # Create a mock for WeasyPrint
        mock_html = MagicMock()
        mock_html.write_pdf.return_value = b"%PDF-1.4 mock pdf content"

        mock_weasyprint = MagicMock()
        mock_weasyprint.HTML.return_value = mock_html
        # setitem restores any real weasyprint afterwards instead of dropping it
        monkeypatch.setitem(sys.modules, "weasyprint", mock_weasyprint)

        result = export_receipt(
            sample_receipt,
            format=ReceiptExportFormat.PDF,
            options=export_options,
        )

        # Should be bytes
        assert isinstance(result, bytes)
        assert result.startswith(b"%PDF")

        # HTML should have been generated from receipt
        mock_weasyprint.HTML.assert_called_once()
        mock_html.write_pdf.assert_called_once()

    def test_export_receipt_pdf_requires_weasyprint(self, sample_receipt, export_options):
        """Test PDF export raises ImportError without WeasyPrint."""
        import sys

        # Remove weasyprint from sys.modules if present
        original_weasyprint = sys.modules.pop("weasyprint", None)

        try:
            # Mock import failure
            import builtins

            original_import = builtins.__import__

            def mock_import(name, *args, **kwargs):
                if name == "weasyprint":
                    raise ImportError("No module named 'weasyprint'")
                return original_import(name, *args, **kwargs)

            builtins.__import__ = mock_import

            try:
                with pytest.raises(ImportError) as exc_info:
                    export_receipt(
                        sample_receipt,
                        format=ReceiptExportFormat.PDF,
                        options=export_options,
                    )
                assert "weasyprint" in str(exc_info.value).lower()
            finally:
                builtins.__import__ = original_import
        finally:
            # Restore weasyprint if it was present
            if original_weasyprint is not None:
                sys.modules["weasyprint"] = original_weasyprint

    def test_export_receipt_pdf_to_file(self, sample_receipt, tmp_path):
        """Test exporting receipt PDF directly to file."""
        if not is_pdf_export_available():
            pytest.skip("WeasyPrint native dependencies unavailable")

        output_path = tmp_path / "receipt.pdf"

        result_path = _render_pdf_in_child(sample_receipt, str(output_path)).stdout.decode()

        # Should return the path
        assert result_path == str(output_path)
        # File should exist
        assert output_path.exists()
        # File should contain PDF content
        with open(output_path, "rb") as f:
            content = f.read()
        assert content[:4] == b"%PDF"

    def test_export_receipt_pdf_to_file_with_mock(self, sample_receipt, tmp_path, monkeypatch):
        """Test PDF file export with mocked WeasyPrint."""
        mock_html = MagicMock()
        mock_html.write_pdf.return_value = b"%PDF-1.4 mock pdf content for file"

        mock_weasyprint = MagicMock()
        mock_weasyprint.HTML.return_value = mock_html
        monkeypatch.setitem(sys.modules, "weasyprint", mock_weasyprint)

        output_path = tmp_path / "receipt_mock.pdf"

        result_path = export_receipt_pdf_to_file(
            sample_receipt,
            str(output_path),
        )

        # Should return the path
        assert result_path == str(output_path)
        # File should exist
        assert output_path.exists()
        # File should contain mock PDF content
        with open(output_path, "rb") as f:
            content = f.read()
        assert content == b"%PDF-1.4 mock pdf content for file"


# ============================================================================
# Bundle Export Tests
# ============================================================================


class TestBundleExport:
    """Tests for bundle export functionality."""

    def test_export_receipts_bundle(self, sample_receipt, export_options):
        """Test exporting multiple receipts as bundle."""
        receipts = [sample_receipt, sample_receipt]

        result = export_receipts_bundle(
            receipts,
            format=ReceiptExportFormat.JSON,
            options=export_options,
        )

        parsed = json.loads(result)

        # Should be an array or have receipts key
        assert isinstance(parsed, (list, dict))
        if isinstance(parsed, dict):
            assert "receipts" in parsed or "items" in parsed

    def test_export_empty_bundle(self, export_options):
        """Test exporting empty bundle."""
        result = export_receipts_bundle(
            [],
            format=ReceiptExportFormat.JSON,
            options=export_options,
        )

        parsed = json.loads(result)
        # Should handle empty gracefully
        assert parsed is not None


# ============================================================================
# Streaming Export Tests
# ============================================================================


class TestStreamingExport:
    """Tests for streaming export functionality."""

    def test_stream_receipt_json(self, sample_receipt):
        """Test streaming JSON export."""
        chunks = list(stream_receipt_json(sample_receipt))

        # Should produce chunks
        assert len(chunks) > 0

        # Combined should be valid JSON
        combined = "".join(chunks)
        parsed = json.loads(combined)
        assert parsed["id"] == "receipt_001"


# ============================================================================
# Options Filtering Tests
# ============================================================================


class TestOptionsFiltering:
    """Tests for export options filtering."""

    def test_exclude_export_metadata(self, sample_receipt):
        """Test excluding export metadata from output."""
        options = ExportOptions(include_export_metadata=False)
        result = export_receipt(
            sample_receipt,
            format=ReceiptExportFormat.JSON,
            options=options,
        )

        parsed = json.loads(result)
        # _export metadata should be excluded when include_export_metadata=False
        assert "_export" not in parsed

    def test_include_export_metadata(self, sample_receipt):
        """Test including export metadata in output."""
        options = ExportOptions(include_export_metadata=True)
        result = export_receipt(
            sample_receipt,
            format=ReceiptExportFormat.JSON,
            options=options,
        )

        parsed = json.loads(result)
        # _export metadata should be included
        assert "_export" in parsed
        assert "format" in parsed["_export"]
        assert "exported_at" in parsed["_export"]

    def test_exclude_provenance(self, sample_receipt):
        """Test excluding provenance chain from export."""
        # Add provenance_chain to the mock receipt's to_dict return
        mock_dict = sample_receipt.to_dict.return_value.copy()
        mock_dict["provenance_chain"] = [{"event": "test"}]
        sample_receipt.to_dict.return_value = mock_dict

        options = ExportOptions(include_provenance=False)
        result = export_receipt(
            sample_receipt,
            format=ReceiptExportFormat.JSON,
            options=options,
        )

        parsed = json.loads(result)
        # provenance_chain should be excluded when include_provenance=False
        assert "provenance_chain" not in parsed

    def test_exclude_config(self, sample_receipt):
        """Test excluding config from export."""
        # Add config_used to the mock receipt's to_dict return
        mock_dict = sample_receipt.to_dict.return_value.copy()
        mock_dict["config_used"] = {"setting": "value"}
        sample_receipt.to_dict.return_value = mock_dict

        options = ExportOptions(include_config=False)
        result = export_receipt(
            sample_receipt,
            format=ReceiptExportFormat.JSON,
            options=options,
        )

        parsed = json.loads(result)
        # config_used should be excluded when include_config=False
        assert "config_used" not in parsed


# ============================================================================
# Edge Cases
# ============================================================================


class TestEdgeCases:
    """Tests for edge cases in export."""

    def test_receipt_with_special_characters(self):
        """Test receipt with special characters in content."""
        receipt = MagicMock()
        receipt.id = "receipt_special"
        receipt.decision = "Use \"quotes\" and <tags> and 'apostrophes'"
        receipt.question = "Test?"
        receipt.confidence = 0.5
        receipt.timestamp = datetime.now()
        receipt.to_dict = MagicMock(
            return_value={
                "id": receipt.id,
                "decision": receipt.decision,
                "question": receipt.question,
                "confidence": receipt.confidence,
                "timestamp": receipt.timestamp.isoformat(),
            }
        )

        result = export_receipt(receipt, format=ReceiptExportFormat.JSON)

        # Should handle special chars
        parsed = json.loads(result)
        assert "quotes" in parsed["decision"]

    def test_receipt_with_unicode(self):
        """Test receipt with unicode content."""
        receipt = MagicMock()
        receipt.id = "receipt_unicode"
        receipt.decision = "Décision avec accénts et émojis 🚀"
        receipt.question = "测试中文?"
        receipt.confidence = 0.8
        receipt.timestamp = datetime.now()
        receipt.to_dict = MagicMock(
            return_value={
                "id": receipt.id,
                "decision": receipt.decision,
                "question": receipt.question,
                "confidence": receipt.confidence,
                "timestamp": receipt.timestamp.isoformat(),
            }
        )

        result = export_receipt(receipt, format=ReceiptExportFormat.JSON)

        parsed = json.loads(result)
        assert "accénts" in parsed["decision"]

    def test_receipt_with_empty_fields(self):
        """Test receipt with empty optional fields."""
        receipt = MagicMock()
        receipt.id = "receipt_minimal"
        receipt.decision = "Decision"
        receipt.question = "Question"
        receipt.confidence = 0.5
        receipt.timestamp = datetime.now()
        receipt.key_arguments = []
        receipt.dissenting_views = []
        receipt.evidence_cited = []
        receipt.to_dict = MagicMock(
            return_value={
                "id": receipt.id,
                "decision": receipt.decision,
                "question": receipt.question,
                "confidence": receipt.confidence,
                "timestamp": receipt.timestamp.isoformat(),
                "key_arguments": [],
                "dissenting_views": [],
                "evidence_cited": [],
            }
        )

        result = export_receipt(receipt, format=ReceiptExportFormat.JSON)

        parsed = json.loads(result)
        assert parsed["id"] == "receipt_minimal"
