'use client';

import { useState, useRef, useEffect, useCallback } from 'react';
import { useBroadcast } from '@/hooks/useBroadcast';
import type { PublishDropdownProps } from './types';

/**
 * Dropdown menu for publishing to Twitter/X and YouTube
 */
export function PublishDropdown({ debateId, title }: PublishDropdownProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [publishing, setPublishing] = useState<string | null>(null);
  const [result, setResult] = useState<{ type: 'success' | 'error'; message: string } | null>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);
  const { publishToTwitter, publishToYouTube } = useBroadcast(debateId);

  // Close on outside click
  useEffect(() => {
    const handleClick = (e: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(e.target as Node)) {
        setIsOpen(false);
      }
    };
    document.addEventListener('mousedown', handleClick);
    return () => document.removeEventListener('mousedown', handleClick);
  }, []);

  // Clear result after timeout
  useEffect(() => {
    if (result) {
      const timer = setTimeout(() => setResult(null), 3000);
      return () => clearTimeout(timer);
    }
  }, [result]);

  const handleTwitter = useCallback(async () => {
    setPublishing('twitter');
    setResult(null);
    try {
      const response = await publishToTwitter(title || `Aragora Debate: ${debateId}`);
      if (response.success) {
        setResult({ type: 'success', message: 'Posted to Twitter!' });
        setIsOpen(false);
      } else {
        setResult({ type: 'error', message: response.error || 'Failed to post' });
      }
    } catch (e) {
      setResult({ type: 'error', message: e instanceof Error ? e.message : 'Failed to post' });
    } finally {
      setPublishing(null);
    }
  }, [debateId, title, publishToTwitter]);

  const handleYouTube = useCallback(async () => {
    setPublishing('youtube');
    setResult(null);
    try {
      const response = await publishToYouTube(
        title || 'Aragora Debate',
        `Multi-agent debate on: ${title || debateId}\n\nGenerated by Aragora - https://aragora.ai`,
      );
      if (response.success) {
        setResult({ type: 'success', message: 'Uploaded to YouTube!' });
        setIsOpen(false);
      } else {
        setResult({ type: 'error', message: response.error || 'Failed to upload' });
      }
    } catch (e) {
      setResult({ type: 'error', message: e instanceof Error ? e.message : 'Failed to upload' });
    } finally {
      setPublishing(null);
    }
  }, [debateId, title, publishToYouTube]);

  return (
    <div className="relative" ref={dropdownRef}>
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="px-2 py-1 text-xs font-theme-data border border-accent/40 hover:bg-accent/10 transition-colors"
        aria-haspopup="true"
        aria-expanded={isOpen}
      >
        [PUBLISH {isOpen ? '▲' : '▼'}]
      </button>

      {isOpen && (
        <div className="absolute right-0 mt-1 py-1 bg-surface border border-accent/30 shadow-lg z-50 min-w-[160px]">
          <button
            onClick={handleTwitter}
            disabled={publishing === 'twitter'}
            className="w-full px-3 py-2 text-xs font-theme-data text-left hover:bg-accent/10 disabled:opacity-50 transition-colors"
          >
            {publishing === 'twitter' ? 'Posting...' : 'Twitter/X'}
          </button>
          <button
            onClick={handleYouTube}
            disabled={publishing === 'youtube'}
            className="w-full px-3 py-2 text-xs font-theme-data text-left hover:bg-accent/10 disabled:opacity-50 transition-colors"
          >
            {publishing === 'youtube' ? 'Uploading...' : 'YouTube'}
          </button>
        </div>
      )}

      {result && (
        <div
          className={`absolute right-0 mt-1 px-3 py-2 text-xs font-theme-data z-50 ${
            result.type === 'success'
              ? 'bg-success/20 text-success border border-success/40'
              : 'bg-warning/20 text-warning border border-warning/40'
          }`}
        >
          {result.message}
        </div>
      )}
    </div>
  );
}
