"""Targeted OpenAPI contract overrides for autogenerated handler routes.

These routes are discovered from handler metadata and route maps, but they need
explicit request-body metadata to keep the published contract truthful.
"""

from __future__ import annotations

from typing import Any


def _json_body(
    description: str,
    *,
    properties: dict[str, Any] | None = None,
    required_fields: list[str] | None = None,
    required: bool = True,
) -> dict[str, Any]:
    schema: dict[str, Any] = {"type": "object"}
    if properties:
        schema["properties"] = properties
    if required_fields:
        schema["required"] = required_fields

    return {
        "description": description,
        "required": required,
        "content": {
            "application/json": {
                "schema": schema,
            }
        },
    }


def _operation(
    summary: str,
    description: str,
    *,
    tags: list[str] | None = None,
) -> dict[str, Any]:
    operation: dict[str, Any] = {
        "summary": summary,
        "description": description,
    }
    if tags:
        operation["tags"] = tags
    return operation


ROUTE_CONTRACT_OVERRIDES: dict[str, dict[str, dict[str, Any]]] = {
    "/api/v1/inbox/command": {
        "get": _operation(
            "Fetch inbox command center view",
            "Fetch prioritized inbox messages with aggregate stats and command-center filters.",
            tags=["Inbox"],
        )
    },
    "/api/v1/inbox/connect": {
        "post": {
            "summary": "Connect unified inbox account",
            "description": "Exchange an OAuth authorization code for a Gmail or Outlook inbox account.",
            "requestBody": _json_body(
                "Unified inbox connection request.",
                required_fields=["provider", "auth_code"],
                properties={
                    "provider": {"type": "string", "enum": ["gmail", "outlook"]},
                    "auth_code": {"type": "string"},
                    "redirect_uri": {"type": "string", "format": "uri"},
                },
            ),
        }
    },
    "/api/v1/inbox/messages/{message_id}/debate": {
        "post": {
            "summary": "Create inbox message debate",
            "description": "Stage a receipt-backed review or trust-wedge debate for a unified inbox message.",
            "requestBody": _json_body(
                "Optional trust-wedge debate configuration.",
                required=False,
                properties={
                    "allowed_actions": {"type": "array", "items": {"type": "string"}},
                    "label_id": {"type": "string"},
                    "provider_route": {"type": "string"},
                    "expires_in_hours": {"type": "integer"},
                    "auto_approve": {"type": "boolean"},
                    "auto_execute": {"type": "boolean"},
                },
            ),
        }
    },
    "/api/v1/inbox/triage": {
        "post": {
            "summary": "Run unified inbox triage",
            "description": "Run multi-agent triage across one or more unified inbox messages.",
            "requestBody": _json_body(
                "Unified inbox triage request.",
                required_fields=["message_ids"],
                properties={
                    "message_ids": {"type": "array", "items": {"type": "string"}},
                    "context": {"type": "object", "additionalProperties": True},
                },
            ),
        }
    },
    "/api/v1/inbox/bulk-action": {
        "post": {
            "summary": "Execute unified inbox bulk action",
            "description": "Execute a bulk action against specific unified inbox messages.",
            "requestBody": _json_body(
                "Unified inbox bulk-action request.",
                required_fields=["message_ids", "action"],
                properties={
                    "message_ids": {"type": "array", "items": {"type": "string"}},
                    "action": {"type": "string"},
                    "receipt_id": {"type": "string"},
                },
            ),
        }
    },
    "/api/v1/inbox/actions": {
        "post": {
            "summary": "Execute inbox quick action",
            "description": "Execute an inbox command-center action against selected email IDs.",
            "responses": {
                "200": {
                    "description": "OK",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "required": ["success", "action", "processed", "results"],
                                "properties": {
                                    "success": {"type": "boolean"},
                                    "action": {"type": "string"},
                                    "processed": {"type": "integer"},
                                    "results": {
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "additionalProperties": True,
                                        },
                                    },
                                },
                            }
                        }
                    },
                }
            },
            "requestBody": _json_body(
                "Inbox quick-action request.",
                required_fields=["action", "emailIds"],
                properties={
                    "action": {"type": "string"},
                    "emailIds": {"type": "array", "items": {"type": "string"}},
                    "params": {"type": "object", "additionalProperties": True},
                    "receipt_id": {"type": "string"},
                    "actor_id": {"type": "string"},
                },
            ),
        }
    },
    "/api/v1/inbox/bulk-actions": {
        "post": {
            "summary": "Execute inbox bulk action by filter",
            "description": "Execute an inbox command-center bulk action against messages selected by filter.",
            "requestBody": _json_body(
                "Inbox bulk-action-by-filter request.",
                required_fields=["action", "filter"],
                properties={
                    "action": {"type": "string"},
                    "filter": {"type": "string"},
                    "params": {"type": "object", "additionalProperties": True},
                    "receipt_id": {"type": "string"},
                    "actor_id": {"type": "string"},
                },
            ),
        }
    },
    "/api/v1/inbox/sender-profile": {
        "get": _operation(
            "Get inbox sender profile",
            "Get profile information for a sender from the inbox command center.",
            tags=["Inbox"],
        )
    },
    "/api/v1/inbox/daily-digest": {
        "get": _operation(
            "Get inbox daily digest",
            "Get daily digest statistics for the inbox command center.",
            tags=["Inbox"],
        )
    },
    "/api/v1/inbox/reprioritize": {
        "post": {
            "summary": "Reprioritize inbox",
            "description": "Trigger inbox reprioritization, optionally scoped to selected emails.",
            "requestBody": _json_body(
                "Inbox reprioritization request.",
                properties={
                    "emailIds": {"type": "array", "items": {"type": "string"}},
                    "force_tier": {"type": "string"},
                    "auto_debate": {"type": "boolean"},
                },
            ),
        }
    },
    "/api/v1/coordination/workspaces": {
        "get": _operation(
            "List coordination workspaces",
            "List registered workspaces available for cross-workspace coordination.",
            tags=["Coordination"],
        ),
        "post": {
            "summary": "Register coordination workspace",
            "description": "Register a workspace for cross-workspace coordination.",
            "requestBody": _json_body(
                "Workspace registration request.",
                required_fields=["id"],
                properties={
                    "id": {"type": "string"},
                    "name": {"type": "string"},
                    "org_id": {"type": "string"},
                    "federation_mode": {"type": "string"},
                    "endpoint_url": {"type": "string", "format": "uri"},
                    "supports_agent_execution": {"type": "boolean"},
                    "supports_workflow_execution": {"type": "boolean"},
                    "supports_knowledge_query": {"type": "boolean"},
                },
            ),
        },
    },
    "/api/v1/coordination/workspaces/{workspace_id}": {
        "delete": _operation(
            "Unregister coordination workspace",
            "Unregister a workspace from cross-workspace coordination.",
            tags=["Coordination"],
        )
    },
    "/api/v1/coordination/federation": {
        "get": _operation(
            "List coordination federation policies",
            "List federation policies configured for cross-workspace coordination.",
            tags=["Coordination"],
        ),
        "post": {
            "summary": "Create coordination federation policy",
            "description": "Create a federation policy for cross-workspace coordination.",
            "requestBody": _json_body(
                "Federation policy creation request.",
                required_fields=["name"],
                properties={
                    "name": {"type": "string"},
                    "description": {"type": "string"},
                    "mode": {"type": "string"},
                    "sharing_scope": {"type": "string"},
                    "allowed_operations": {"type": "array", "items": {"type": "string"}},
                    "max_requests_per_hour": {"type": "integer"},
                    "require_approval": {"type": "boolean"},
                    "audit_all_requests": {"type": "boolean"},
                    "workspace_id": {"type": "string"},
                    "source_workspace_id": {"type": "string"},
                    "target_workspace_id": {"type": "string"},
                },
            ),
        },
    },
    "/api/v1/coordination/executions": {
        "get": _operation(
            "List coordination executions",
            "List cross-workspace coordination execution requests and their status.",
            tags=["Coordination"],
        )
    },
    "/api/v1/coordination/execute": {
        "post": {
            "summary": "Execute cross-workspace request",
            "description": "Execute an approved cross-workspace coordination request.",
            "requestBody": _json_body(
                "Cross-workspace execution request.",
                required_fields=["operation", "source_workspace_id", "target_workspace_id"],
                properties={
                    "operation": {"type": "string"},
                    "source_workspace_id": {"type": "string"},
                    "target_workspace_id": {"type": "string"},
                    "payload": {"type": "object", "additionalProperties": True},
                    "timeout_seconds": {"type": "number"},
                    "requester_id": {"type": "string"},
                    "consent_id": {"type": "string"},
                },
            ),
        }
    },
    "/api/v1/coordination/consent": {
        "get": _operation(
            "List coordination consents",
            "List data-sharing consents granted between workspaces.",
            tags=["Coordination"],
        ),
        "post": {
            "summary": "Grant coordination consent",
            "description": "Grant data-sharing consent between workspaces.",
            "requestBody": _json_body(
                "Coordination consent request.",
                required_fields=["source_workspace_id", "target_workspace_id"],
                properties={
                    "source_workspace_id": {"type": "string"},
                    "target_workspace_id": {"type": "string"},
                    "scope": {"type": "string"},
                    "data_types": {"type": "array", "items": {"type": "string"}},
                    "operations": {"type": "array", "items": {"type": "string"}},
                    "granted_by": {"type": "string"},
                    "expires_in_days": {"type": "integer"},
                },
            ),
        },
    },
    "/api/v1/coordination/consent/{consent_id}": {
        "delete": _operation(
            "Revoke coordination consent",
            "Revoke a data-sharing consent between workspaces.",
            tags=["Coordination"],
        )
    },
    "/api/v1/coordination/approve/{request_id}": {
        "post": {
            "summary": "Approve coordination request",
            "description": "Approve a pending coordination execution request.",
            "requestBody": _json_body(
                "Coordination approval request.",
                properties={
                    "approved_by": {"type": "string"},
                },
            ),
        }
    },
    "/api/v1/coordination/stats": {
        "get": _operation(
            "Get coordination statistics",
            "Get summary statistics for the cross-workspace coordination subsystem.",
            tags=["Coordination"],
        )
    },
    "/api/v1/coordination/health": {
        "get": _operation(
            "Get coordination health",
            "Return public health for the cross-workspace coordination subsystem.",
            tags=["Coordination"],
        )
    },
}


__all__ = ["ROUTE_CONTRACT_OVERRIDES"]
