from __future__ import annotations

import json

from aragora.blockchain.receipt_anchor import ReceiptAnchor
from aragora.server.handlers import ALL_HANDLERS
from aragora.server.handlers.gauntlet import GauntletHandler
from aragora.server.handlers.gauntlet.receipts import GauntletReceiptsMixin
from aragora.server.handlers.receipts import ReceiptsHandler
from aragora.server.openapi import generate_openapi_schema
from aragora.tenancy.record_scope import OrgScope


def test_receipt_delivery_anchor_handlers_participate_in_all_handlers() -> None:
    handlers = set(ALL_HANDLERS)

    assert ReceiptsHandler in handlers
    assert GauntletHandler in handlers


def test_receipt_delivery_anchor_routes_are_not_placeholders() -> None:
    paths = generate_openapi_schema()["paths"]

    expected_operations = {
        "/api/v1/receipts/deliveries": "listReceiptDeliveries",
        "/api/v1/receipts/recent-anchors": "listRecentReceiptAnchors",
        "/api/v1/receipts/{receipt_id}/anchor-status": "getReceiptAnchorStatus",
    }

    for path, operation_id in expected_operations.items():
        operation = paths[path]["get"]
        assert operation["operationId"] == operation_id
        assert operation.get("x-autogenerated") is not True


def test_receipt_delivery_anchor_routes_match_handler_methods() -> None:
    paths = generate_openapi_schema()["paths"]

    assert set(paths["/api/v1/receipts/deliveries"]) & {"get"} == {"get"}
    assert set(paths["/api/v1/receipts/recent-anchors"]) & {"get"} == {"get"}
    assert set(paths["/api/v1/receipts/{receipt_id}/anchor-status"]) & {"get"} == {"get"}


def test_recent_anchor_response_contract_matches_handler_fields() -> None:
    schema = generate_openapi_schema()["paths"]["/api/v1/receipts/recent-anchors"]["get"][
        "responses"
    ]["200"]["content"]["application/json"]["schema"]
    properties = schema["properties"]

    mixin = GauntletReceiptsMixin.__new__(GauntletReceiptsMixin)
    mixin._receipt_anchor = ReceiptAnchor()
    result = GauntletReceiptsMixin._get_recent_anchors.__wrapped__(
        mixin, {"limit": "7"}, scope=OrgScope(org_id="org-a", user_id="user-a", role="admin")
    )
    body = json.loads(result.body)

    assert result.status_code == 200
    assert {"anchors", "total", "limit"} <= set(properties)
    assert "count" not in properties
    assert {"anchors", "total", "limit"} <= set(body)
    assert body["limit"] == 7
