"""Regression coverage for free-function registered OpenAPI routes."""

import ast
from collections import Counter
import json
from pathlib import Path

import yaml

from aragora.server.openapi import generate_openapi_schema
from aragora.server.openapi.endpoints.wired_registrations import (
    WIRED_REGISTRATION_ENDPOINTS,
    _PRESERVED_OPERATION_IDS,
)
from aragora.server.openapi.operation_ids import generate_operation_id
from aragora.server.openapi_impl import _is_source_backed_registration


_ROOT = Path(__file__).parents[3]
_REGISTRARS = {
    "aragora/server/handlers/admin/credits.py": "register_credits_admin_routes",
    "aragora/server/handlers/inbox_command.py": "register_routes",
    "aragora/server/handlers/features/integrations.py": "register_integration_routes",
    "aragora/server/handlers/payments/plans.py": "register_payment_routes",
    "aragora/server/handlers/costs/routes.py": "register_routes",
}
# Registrar modules that moved on disk while their wired-registration source
# label (baked into the exported OpenAPI descriptions) stayed on the flat path.
_REGISTRAR_SOURCE_PATHS = {
    "aragora/server/handlers/inbox_command.py": "aragora/server/handlers/inbox/inbox_command.py",
}


def _literal_registrar_operations(source: str, function_name: str) -> set[tuple[str, str]]:
    tree = ast.parse((_ROOT / _REGISTRAR_SOURCE_PATHS.get(source, source)).read_text())
    function = next(
        node
        for node in tree.body
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == function_name
    )
    operations: set[tuple[str, str]] = set()
    for node in ast.walk(function):
        if not isinstance(node, ast.Call) or not isinstance(node.func, ast.Attribute):
            continue
        if not node.func.attr.startswith("add_") or not node.args:
            continue
        path = node.args[0]
        if isinstance(path, ast.Constant) and isinstance(path.value, str):
            operations.add((path.value, node.func.attr.removeprefix("add_")))
    return operations


def test_wired_registration_routes_survive_fresh_generation() -> None:
    paths = generate_openapi_schema()["paths"]

    assert len(WIRED_REGISTRATION_ENDPOINTS) == 57
    assert (
        sum(
            method in {"delete", "get", "patch", "post", "put"}
            for methods in WIRED_REGISTRATION_ENDPOINTS.values()
            for method in methods
        )
        == 68
    )
    for path, expected_methods in WIRED_REGISTRATION_ENDPOINTS.items():
        assert path in paths
        for method in expected_methods:
            if method.startswith("x-"):
                continue
            assert method in paths[path], f"{method.upper()} {path} missing from generated spec"


def test_wired_registration_metadata_is_explicit() -> None:
    for path, methods in WIRED_REGISTRATION_ENDPOINTS.items():
        for method, operation in methods.items():
            if method.startswith("x-"):
                continue
            assert operation["x-method-inferred"] is False
            assert "x-autogenerated" not in operation
            assert operation["x-wired-registration"] is True
            assert operation["summary"] == f"{method.upper()} {path}"
            assert "Served route registered by" in operation["description"]


def test_wired_operation_ids_are_unique() -> None:
    operation_ids = [
        operation["operationId"]
        for methods in WIRED_REGISTRATION_ENDPOINTS.values()
        for method, operation in methods.items()
        if not method.startswith("x-")
    ]

    assert len(operation_ids) == 68
    assert len(set(operation_ids)) == 68


def test_canonical_wired_routes_own_unsuffixed_generated_operation_ids() -> None:
    for path, methods in WIRED_REGISTRATION_ENDPOINTS.items():
        if not path.startswith("/api/v1/"):
            continue
        for method, operation in methods.items():
            if (path, method) in _PRESERVED_OPERATION_IDS:
                continue
            assert operation["operationId"] == generate_operation_id(method, path)


def test_wired_operation_ids_match_generated_json_and_yaml() -> None:
    json_spec = json.loads((_ROOT / "docs/api/openapi_generated.json").read_text())
    yaml_spec = yaml.safe_load((_ROOT / "docs/api/openapi_generated.yaml").read_text())
    json_ids = Counter(
        operation["operationId"]
        for methods in json_spec["paths"].values()
        for operation in methods.values()
        if isinstance(operation, dict) and "operationId" in operation
    )
    yaml_ids = Counter(
        operation["operationId"]
        for methods in yaml_spec["paths"].values()
        for operation in methods.values()
        if isinstance(operation, dict) and "operationId" in operation
    )

    for path, methods in WIRED_REGISTRATION_ENDPOINTS.items():
        for method, operation in methods.items():
            expected = operation["operationId"]
            assert json_spec["paths"][path][method]["operationId"] == expected
            assert yaml_spec["paths"][path][method]["operationId"] == expected
            assert json_ids[expected] == 1
            assert yaml_ids[expected] == 1


def test_cost_metadata_survives_json_yaml_and_typescript_generation() -> None:
    json_spec = json.loads((_ROOT / "docs/api/openapi_generated.json").read_text())
    yaml_spec = yaml.safe_load((_ROOT / "docs/api/openapi_generated.yaml").read_text())
    typescript = (_ROOT / "sdk/typescript/src/openapi-types.ts").read_text()
    contracts = {
        ("", "get"): ("Get recommendation", "Get a specific cost optimization recommendation."),
        ("/apply", "post"): ("Apply recommendation", "Apply a cost optimization recommendation."),
        ("/dismiss", "post"): (
            "Dismiss recommendation",
            "Dismiss a cost optimization recommendation.",
        ),
    }

    for prefix in (
        "/api/costs/recommendations/{recommendation_id}",
        "/api/v1/costs/recommendations/{recommendation_id}",
    ):
        for (suffix, method), (summary, description) in contracts.items():
            path = f"{prefix}{suffix}"
            for spec in (json_spec, yaml_spec):
                assert spec["paths"][path][method]["summary"] == summary
                assert spec["paths"][path][method]["description"] == description
            path_block = typescript.split(f'    "{path}": {{', 1)[1].split('\n    "/api/', 1)[0]
            assert f"* {summary}" in path_block
            assert f"* @description {description}" in path_block


def test_existing_wired_operation_ids_remain_stable() -> None:
    json_spec = json.loads((_ROOT / "docs/api/openapi_generated.json").read_text())
    yaml_spec = yaml.safe_load((_ROOT / "docs/api/openapi_generated.yaml").read_text())
    expected = {
        ("/api/v1/inbox/actions", "post"): "createInboxActions",
        ("/api/v1/inbox/bulk-actions", "post"): "createInboxBulkActions",
        ("/api/v1/inbox/command", "get"): "listInboxCommand",
        ("/api/v1/inbox/daily-digest", "get"): "listInboxDailyDigest",
        ("/api/v1/inbox/reprioritize", "post"): "createInboxReprioritize",
        ("/api/v1/inbox/sender-profile", "get"): "listInboxSenderProfile",
        (
            "/api/v1/costs/recommendations/{recommendation_id}",
            "get",
        ): "handle_get_recommendation",
        (
            "/api/v1/costs/recommendations/{recommendation_id}/apply",
            "post",
        ): "handle_apply_recommendation",
        (
            "/api/v1/costs/recommendations/{recommendation_id}/dismiss",
            "post",
        ): "handle_dismiss_recommendation",
    }

    for (path, method), operation_id in expected.items():
        assert json_spec["paths"][path][method]["operationId"] == operation_id
        assert yaml_spec["paths"][path][method]["operationId"] == operation_id


def test_unversioned_only_email_routes_do_not_gain_v1_aliases() -> None:
    paths = generate_openapi_schema()["paths"]

    assert "/api/email/daily-digest" in paths
    assert "/api/email/sender-profile" in paths
    assert "/api/v1/email/daily-digest" not in paths
    assert "/api/v1/email/sender-profile" not in paths
    assert set(paths["/api/email/daily-digest"]) == {"get"}
    assert set(paths["/api/email/sender-profile"]) == {"get"}


def test_wired_routes_are_source_backed_not_autogenerated_placeholders() -> None:
    paths = generate_openapi_schema()["paths"]

    for path, methods in WIRED_REGISTRATION_ENDPOINTS.items():
        for method in methods:
            assert paths[path][method].get("x-autogenerated") is not True


def test_canonical_wired_routes_do_not_inherit_legacy_metadata() -> None:
    paths = generate_openapi_schema()["paths"]

    canonical_operations = (
        ("/api/v1/inbox/actions", "post"),
        ("/api/v1/payments/authorize", "post"),
        ("/api/v1/costs/recommendations/{recommendation_id}", "get"),
    )
    for path, method in canonical_operations:
        operation = paths[path][method]
        assert operation.get("deprecated") is not True
        assert operation["x-aragora-stability"] != "deprecated"
        assert operation["summary"] != f"{method.upper()} {path.replace('/api/v1/', '/api/')}"


def test_inbox_quick_action_response_matches_runtime_shape() -> None:
    response_schema = generate_openapi_schema()["paths"]["/api/v1/inbox/actions"]["post"][
        "responses"
    ]["200"]["content"]["application/json"]["schema"]

    assert response_schema["required"] == ["success", "action", "processed", "results"]
    assert response_schema["properties"] == {
        "success": {"type": "boolean"},
        "action": {"type": "string"},
        "processed": {"type": "integer"},
        "results": {
            "type": "array",
            "items": {"type": "object", "additionalProperties": True},
        },
    }


def test_cost_recommendation_mutations_are_exported() -> None:
    paths = generate_openapi_schema()["paths"]

    for version_prefix in ("/api/", "/api/v1/"):
        for action in ("apply", "dismiss"):
            path = f"{version_prefix}costs/recommendations/{{recommendation_id}}/{action}"
            assert "post" in paths[path]


def test_wired_declarations_match_all_registrar_sources() -> None:
    for source, function_name in _REGISTRARS.items():
        registered = _literal_registrar_operations(source, function_name)
        declared = {
            (path, method)
            for path, methods in WIRED_REGISTRATION_ENDPOINTS.items()
            for method, operation in methods.items()
            if not method.startswith("x-")
            and f"registered by {source}." in operation["description"]
        }
        assert declared
        assert declared <= registered, (
            f"{source} has unserved declarations: {declared - registered}"
        )


def test_payment_webhooks_match_runtime_bearer_auth() -> None:
    paths = generate_openapi_schema()["paths"]

    for path in (
        "/api/payments/webhook/authnet",
        "/api/v1/payments/webhook/authnet",
        "/api/payments/webhook/stripe",
        "/api/v1/payments/webhook/stripe",
    ):
        assert paths[path]["post"]["security"] == [{"bearerAuth": []}]


def test_wired_operations_do_not_share_mutable_schema_objects() -> None:
    charge = WIRED_REGISTRATION_ENDPOINTS["/api/payments/charge"]["post"]
    refund = WIRED_REGISTRATION_ENDPOINTS["/api/payments/refund"]["post"]
    charge_response = charge["responses"]["200"]["content"]["application/json"]["schema"]
    charge_request = charge["requestBody"]["content"]["application/json"]["schema"]
    refund_response = refund["responses"]["200"]["content"]["application/json"]["schema"]

    assert charge_response is not charge_request
    assert charge_response is not refund_response


def test_source_backed_bypass_is_limited_to_canonical_wired_paths() -> None:
    marked = {"get": {"x-wired-registration": True}}

    assert _is_source_backed_registration("/api/admin/credits/{org_id}", marked)
    assert not _is_source_backed_registration("/api/unrelated", marked)
