"""Tests for dropping autogenerated bare-route placeholders no dispatcher serves."""

from __future__ import annotations

from aragora.server.openapi_impl import (
    _UNSERVED_BARE_PLACEHOLDER_PATHS,
    _drop_unserved_bare_placeholders,
    generate_openapi_schema,
)


def _autogen_spec() -> dict[str, object]:
    return {"get": {"x-autogenerated": True, "responses": {"200": {"description": "ok"}}}}


def test_unserved_placeholders_absent_from_generated_schema() -> None:
    paths = generate_openapi_schema()["paths"]
    for placeholder in _UNSERVED_BARE_PLACEHOLDER_PATHS:
        assert placeholder not in paths


def test_drop_removes_only_fully_autogenerated_specs() -> None:
    curated = {
        "get": {
            "tags": ["SLOs"],
            "operationId": "listSlos",
            "responses": {"200": {"description": "ok"}},
        }
    }
    paths = {
        "/api/slos": _autogen_spec(),
        "/api/v1/slos": curated,
        "/api/v1/memory": _autogen_spec(),
    }

    result = _drop_unserved_bare_placeholders(paths)

    assert "/api/slos" not in result
    assert "/api/v1/memory" not in result
    # A curated (hand-authored) operation on a listed path must survive.
    assert result["/api/v1/slos"] is curated


def test_drop_ignores_unlisted_paths() -> None:
    paths = {"/api/unrelated": _autogen_spec()}
    assert _drop_unserved_bare_placeholders(paths) == paths
