import { existsSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

const require = createRequire(import.meta.url);
const SITE = path.resolve(__dirname, '..');
const DOCS = path.join(SITE, 'docs');

type SidebarItem =
  | string
  | { type: 'doc'; id: string }
  | { type: 'autogenerated'; dirName: string }
  | { type: 'category'; label: string; items: SidebarItem[] }
  | { type: string; [key: string]: unknown };

function collect(items: SidebarItem[], docIds: string[], dirNames: string[]): void {
  for (const item of items) {
    if (typeof item === 'string') {
      docIds.push(item);
    } else if (item.type === 'doc') {
      docIds.push((item as { id: string }).id);
    } else if (item.type === 'autogenerated') {
      dirNames.push((item as { dirName: string }).dirName);
    } else if (Array.isArray((item as { items?: unknown }).items)) {
      collect((item as { items: SidebarItem[] }).items, docIds, dirNames);
    }
  }
}

function loadSidebars(): Record<string, SidebarItem[]> {
  return require(path.join(SITE, 'sidebars.js'));
}

function collectAll(): { docIds: string[]; dirNames: string[] } {
  const docIds: string[] = [];
  const dirNames: string[] = [];
  for (const items of Object.values(loadSidebars())) {
    collect(items, docIds, dirNames);
  }
  return { docIds, dirNames };
}

describe('sidebars.js', () => {
  it('declares every sidebar the navbar links to', () => {
    const sidebars = loadSidebars();
    for (const name of [
      'gettingStartedSidebar',
      'guidesSidebar',
      'apiSidebar',
      'referenceSidebar',
    ]) {
      expect(Array.isArray(sidebars[name]), `${name} missing`).toBe(true);
    }
  });

  it('references only doc ids that resolve to an existing docs file', () => {
    const { docIds } = collectAll();
    expect(docIds.length).toBeGreaterThan(0);
    const missing = docIds.filter(
      (id) => !existsSync(path.join(DOCS, `${id}.md`)) && !existsSync(path.join(DOCS, `${id}.mdx`)),
    );
    expect(missing, `sidebar doc ids without a docs file: ${missing.join(', ')}`).toEqual([]);
  });

  it('points every autogenerated category at an existing docs directory', () => {
    const { dirNames } = collectAll();
    expect(dirNames.length).toBeGreaterThan(0);
    const missing = dirNames.filter((dir) => !existsSync(path.join(DOCS, dir)));
    expect(missing, `autogenerated dirs without a docs directory: ${missing.join(', ')}`).toEqual(
      [],
    );
  });
});
