"""Lazy import mappings for handler modules.

This module provides a mapping of handler names to their module paths,
enabling lazy loading of handlers to reduce import time.
"""

from __future__ import annotations

# Mapping of handler class names to their module paths
# This enables lazy loading - handlers are only imported when accessed
HANDLER_MODULES: dict[str, str] = {
    # admin/ directory
    "AdminHandler": "aragora.server.handlers.admin",
    "SecurityHandler": "aragora.server.handlers.admin",
    "BillingHandler": "aragora.server.handlers.admin",
    "CreditsAdminHandler": "aragora.server.handlers.admin.credits",
    "DashboardHandler": "aragora.server.handlers.admin",
    "EmergencyAccessHandler": "aragora.server.handlers.admin.emergency_access",
    "FeatureFlagAdminHandler": "aragora.server.handlers.admin.feature_flags",
    "HealthHandler": "aragora.server.handlers.admin",
    "LivenessHandler": "aragora.server.handlers.admin.health.liveness",
    "ReadinessHandler": "aragora.server.handlers.admin.health.readiness",
    "StorageHealthHandler": "aragora.server.handlers.admin.health.storage_health",
    "SystemHandler": "aragora.server.handlers.admin",
    # agents/ directory
    "AgentConfigHandler": "aragora.server.handlers.agents",
    "AgentRecommendationHandler": "aragora.server.handlers.agents.recommendations",
    "AgentsHandler": "aragora.server.handlers.agents",
    "CalibrationHandler": "aragora.server.handlers.agents",
    "FeedbackHandler": "aragora.server.handlers.agents.feedback",
    "LeaderboardViewHandler": "aragora.server.handlers.agents",
    "ProbesHandler": "aragora.server.handlers.agents",
    # analytics
    "AnalyticsHandler": "aragora.server.handlers._analytics_impl",
    "AnalyticsDashboardHandler": "aragora.server.handlers.analytics_dashboard",
    "EndpointAnalyticsHandler": "aragora.server.handlers.endpoint_analytics",
    "AnalyticsMetricsHandler": "aragora.server.handlers._analytics_metrics_impl",
    "AnalyticsPerformanceHandler": "aragora.server.handlers.analytics_performance",
    "OutcomeAnalyticsHandler": "aragora.server.handlers.outcome_analytics",
    # autonomous/ directory
    "ApprovalHandler": "aragora.server.handlers.autonomous",
    "AlertHandler": "aragora.server.handlers.autonomous",
    "TriggerHandler": "aragora.server.handlers.autonomous",
    "MonitoringHandler": "aragora.server.handlers.autonomous",
    "AudienceSuggestionsHandler": "aragora.server.handlers.audience_suggestions",
    "AutomationHandler": "aragora.server.handlers.integrations.automation",
    "AutonomousLearningHandler": "aragora.server.handlers.autonomous_learning",
    # approvals inbox
    "UnifiedApprovalsHandler": "aragora.server.handlers.approvals_inbox",
    # bots/ directory
    "DiscordHandler": "aragora.server.handlers.bots",
    "GoogleChatHandler": "aragora.server.handlers.bots",
    "TeamsHandler": "aragora.server.handlers.bots",
    "TelegramHandler": "aragora.server.handlers.bots",
    "WhatsAppHandler": "aragora.server.handlers.bots",
    "ZoomHandler": "aragora.server.handlers.bots",
    # codebase/ directory
    "IntelligenceHandler": "aragora.server.handlers.codebase",
    # connectors/ directory
    "ConnectorManagementHandler": "aragora.server.handlers.connectors.management",
    # debates/ directory
    "DebatesHandler": "aragora.server.handlers.debates",
    "DebateShareHandler": "aragora.server.handlers.debates.share",
    "PublicDebateViewerHandler": "aragora.server.handlers.debates.public_viewer",
    "DecisionPackageHandler": "aragora.server.handlers.debates.decision_package",
    "GraphDebatesHandler": "aragora.server.handlers.debates",
    "MatrixDebatesHandler": "aragora.server.handlers.debates",
    # decisions/ directory
    "DecisionExplainHandler": "aragora.server.handlers.decisions",
    "DecisionPipelineHandler": "aragora.server.handlers.decisions",
    # governance/ directory
    "OutcomeHandler": "aragora.server.handlers.governance",
    # canvas pipeline
    "CanvasPipelineHandler": "aragora.server.handlers.canvas_pipeline",
    "DAGOperationsHandler": "aragora.server.handlers.dag_operations",
    # evolution/ directory
    "EvolutionABTestingHandler": "aragora.server.handlers.evolution",
    "EvolutionHandler": "aragora.server.handlers.evolution",
    # features/ directory - many handlers
    "AuditSessionsHandler": "aragora.server.handlers.features",
    "AudioHandler": "aragora.server.handlers.features",
    "BroadcastHandler": "aragora.server.handlers.features",
    "CloudStorageHandler": "aragora.server.handlers.features",
    "CodebaseAuditHandler": "aragora.server.handlers.features",
    "ConnectorsHandler": "aragora.server.handlers.features",
    "CrossPlatformAnalyticsHandler": "aragora.server.handlers.features",
    "DevOpsHandler": "aragora.server.handlers.features",
    "DocumentHandler": "aragora.server.handlers.features",
    "DocumentBatchHandler": "aragora.server.handlers.features",
    "DocumentQueryHandler": "aragora.server.handlers.features",
    "EmailWebhooksHandler": "aragora.server.handlers.features",
    "EvidenceHandler": "aragora.server.handlers.features",
    "EvidenceEnrichmentHandler": "aragora.server.handlers.features",
    "FeaturesHandler": "aragora.server.handlers.features",
    "FindingWorkflowHandler": "aragora.server.handlers.features",
    "FolderUploadHandler": "aragora.server.handlers.features",
    "GmailIngestHandler": "aragora.server.handlers.features",
    "GmailQueryHandler": "aragora.server.handlers.features",
    "IntegrationsHandler": "aragora.server.handlers.features",
    "LegalHandler": "aragora.server.handlers.features",
    "MarketplaceHandler": "aragora.server.handlers.features",
    "PluginsHandler": "aragora.server.handlers.features",
    "PulseHandler": "aragora.server.handlers.features",
    "ReconciliationHandler": "aragora.server.handlers.features",
    "RLMHandler": "aragora.server.handlers.features",
    "RoutingRulesHandler": "aragora.server.handlers.features",
    "SchedulerHandler": "aragora.server.handlers.features",
    "SmartUploadHandler": "aragora.server.handlers.features",
    "UnifiedInboxHandler": "aragora.server.handlers.features",
    "SharedInboxHandler": "aragora.server.handlers.shared_inbox",
    # features/gmail_* modules
    "GmailLabelsHandler": "aragora.server.handlers.features.gmail_labels",
    "GmailThreadsHandler": "aragora.server.handlers.features.gmail_threads",
    # billing/ directory
    "CostDashboardHandler": "aragora.server.handlers.billing",
    # costs/ directory
    "CostHandler": "aragora.server.handlers.costs",
    # Connector platform handlers (from features/)
    "AdvertisingHandler": "aragora.server.handlers.features",
    "AnalyticsPlatformsHandler": "aragora.server.handlers.features",
    "CRMHandler": "aragora.server.handlers.features",
    "SupportHandler": "aragora.server.handlers.features",
    "EcommerceHandler": "aragora.server.handlers.features",
    "OutlookHandler": "aragora.server.handlers.features.outlook",
    # features/control_plane
    "AgentDashboardHandler": "aragora.server.handlers.features.control_plane",
    # github/ directory
    "AuditGitHubBridgeHandler": "aragora.server.handlers.github.audit_bridge",
    "PRReviewHandler": "aragora.server.handlers.github.pr_review",
    # integrations/ directory
    "IntegrationHealthHandler": "aragora.server.handlers.integrations.health",
    # knowledge/ directory
    "KMCheckpointHandler": "aragora.server.handlers.knowledge.checkpoints",
    "KMAdapterStatusHandler": "aragora.server.handlers.knowledge.adapters",
    "SharingNotificationsHandler": "aragora.server.handlers.knowledge.sharing_notifications",
    # knowledge_base/ directory
    "KnowledgeHandler": "aragora.server.handlers.knowledge_base",
    "KnowledgeMoundHandler": "aragora.server.handlers.knowledge_base",
    # memory/ directory
    "InsightsHandler": "aragora.server.handlers.memory",
    "LearningHandler": "aragora.server.handlers.memory",
    "MemoryHandler": "aragora.server.handlers.memory",
    "MemoryAnalyticsHandler": "aragora.server.handlers.memory",
    "CoordinatorHandler": "aragora.server.handlers.memory",
    "UnifiedMemoryHandler": "aragora.server.handlers.memory.unified_handler",
    # nomic/ directory
    "NomicHandler": "aragora.server.handlers.nomic",
    # public/ directory
    "StatusPageHandler": "aragora.server.handlers.public",
    # notifications/ directory
    "NotificationHistoryHandler": "aragora.server.handlers.notifications.history",
    "NotificationPreferencesHandler": "aragora.server.handlers.notifications.preferences",
    # pipeline/ directory
    "PipelineGraphHandler": "aragora.server.handlers.pipeline_graph",
    "PipelineTransitionsHandler": "aragora.server.handlers.pipeline.transitions",
    "PlanManagementHandler": "aragora.server.handlers.pipeline.plans",
    "ProvenanceExplorerHandler": "aragora.server.handlers.pipeline.provenance_explorer",
    "UniversalGraphHandler": "aragora.server.handlers.pipeline.universal_graph",
    # payments/ directory
    "PaymentRoutesHandler": "aragora.server.handlers.payments.handler",
    # sme/ directory
    "BudgetControlsHandler": "aragora.server.handlers.sme.budget_controls",
    "ReceiptDeliveryHandler": "aragora.server.handlers.sme.receipt_delivery",
    "SlackWorkspaceHandler": "aragora.server.handlers.sme.slack_workspace",
    "TeamsWorkspaceHandler": "aragora.server.handlers.sme.teams_workspace",
    # social/ directory
    "ChannelHealthHandler": "aragora.server.handlers.social.channel_health",
    "DiscordOAuthHandler": "aragora.server.handlers.social.discord_oauth",
    "NotificationsHandler": "aragora.server.handlers.social.notifications",
    "RelationshipHandler": "aragora.server.handlers.social",
    "SharingHandler": "aragora.server.handlers.social.sharing",
    "SlackHandler": "aragora.server.handlers.social",
    "SlackOAuthHandler": "aragora.server.handlers.social.slack_oauth",
    "SocialMediaHandler": "aragora.server.handlers.social",
    "CollaborationHandlers": "aragora.server.handlers.social",
    "get_collaboration_handlers": "aragora.server.handlers.social",
    "TeamsOAuthHandler": "aragora.server.handlers.social.teams_oauth",
    # social/teams
    "TeamsIntegrationHandler": "aragora.server.handlers.social.teams",
    # streaming/ directory
    "StreamingConnectorHandler": "aragora.server.handlers.streaming.handler",
    # tasks/ directory
    "TaskExecutionHandler": "aragora.server.handlers.tasks.execution",
    # verification/ directory
    "FormalVerificationHandler": "aragora.server.handlers.verification",
    "VerificationHandler": "aragora.server.handlers.verification",
    # Top-level handler modules (single file)
    "A2AHandler": "aragora.server.handlers.a2a",
    "ActionCanvasHandler": "aragora.server.handlers.action_canvas",
    "AuditingHandler": "aragora.server.handlers.auditing",
    "AuditTrailHandler": "aragora.server.handlers.audit_trail",
    "SecurityDebateHandler": "aragora.server.handlers.security_debate",
    "AuthHandler": "aragora.server.handlers.auth",
    "BackupHandler": "aragora.server.handlers.backup_handler",
    "BeliefHandler": "aragora.server.handlers.belief",
    "BenchmarkingHandler": "aragora.server.handlers.benchmarking",
    "BindingsHandler": "aragora.server.handlers.bindings",
    "DifferentiationHandler": "aragora.server.handlers.differentiation",
    "BreakpointsHandler": "aragora.server.handlers.breakpoints",
    "DebateInterventionHandler": "aragora.server.handlers.debate_intervention",
    "BudgetHandler": "aragora.server.handlers.budgets",
    "CanvasHandler": "aragora.server.handlers.canvas",
    "CheckpointHandler": "aragora.server.handlers.checkpoints",
    "CodeReviewHandler": "aragora.server.handlers.code_review",
    "ComplianceHandler": "aragora.server.handlers.compliance_handler",
    "ComplianceReportHandler": "aragora.server.handlers.compliance_reports",
    "ContextBudgetHandler": "aragora.server.handlers.context_budget",
    "CompositeHandler": "aragora.server.handlers.composite",
    "ComputerUseHandler": "aragora.server.handlers.computer_use_handler",
    "ConsensusHandler": "aragora.server.handlers.consensus",
    "ControlPlaneHandler": "aragora.server.handlers.control_plane",
    "CoordinationHandler": "aragora.server.handlers.coordination",
    "CritiqueHandler": "aragora.server.handlers.critique",
    "DebateStatsHandler": "aragora.server.handlers.debate_stats",
    "DecisionHandler": "aragora.server.handlers.decision",
    "DeliberationsHandler": "aragora.server.handlers.deliberations",
    "DependencyAnalysisHandler": "aragora.server.handlers.dependency_analysis",
    "DeviceHandler": "aragora.server.handlers.devices",
    "DocsHandler": "aragora.server.handlers.docs",
    "DRHandler": "aragora.server.handlers.dr_handler",
    "EmailDebateHandler": "aragora.server.handlers.email_debate",
    "EmailHandler": "aragora.server.handlers.email",
    "EmailServicesHandler": "aragora.server.handlers.email_services",
    "EmailTriageHandler": "aragora.server.handlers.email_triage",
    "ERC8004Handler": "aragora.server.handlers.erc8004",
    "EvaluationHandler": "aragora.server.handlers.evaluation",
    "ExplainabilityHandler": "aragora.server.handlers.explainability",
    "ExpenseHandler": "aragora.server.handlers.expenses",
    "ExternalAgentsHandler": "aragora.server.handlers.external_agents",
    "ExternalIntegrationsHandler": "aragora.server.handlers.external_integrations",
    "FeatureFlagsHandler": "aragora.server.handlers.feature_flags",
    "FeedbackRoutesHandler": "aragora.server.handlers.feedback",
    "GalleryHandler": "aragora.server.handlers.gallery",
    "GasTownDashboardHandler": "aragora.server.handlers.gastown_dashboard",
    "GatewayAgentsHandler": "aragora.server.handlers.gateway_agents_handler",
    "GatewayConfigHandler": "aragora.server.handlers.gateway_config_handler",
    "GatewayCredentialsHandler": "aragora.server.handlers.gateway_credentials_handler",
    "GatewayHandler": "aragora.server.handlers.gateway_handler",
    "GatewayHealthHandler": "aragora.server.handlers.gateway_health_handler",
    "GauntletHandler": "aragora.server.handlers.gauntlet",
    "GDPRDeletionHandler": "aragora.server.handlers.gdpr_deletion",
    "GenesisHandler": "aragora.server.handlers.genesis",
    "GoalCanvasHandler": "aragora.server.handlers.goal_canvas",
    "HybridDebateHandler": "aragora.server.handlers.hybrid_debate_handler",
    "IdeaCanvasHandler": "aragora.server.handlers.idea_canvas",
    "IntegrationManagementHandler": "aragora.server.handlers.integration_management",
    "IntrospectionHandler": "aragora.server.handlers.introspection",
    "InvoiceHandler": "aragora.server.handlers.invoices",
    "KnowledgeChatHandler": "aragora.server.handlers.knowledge_chat",
    "LaboratoryHandler": "aragora.server.handlers.laboratory",
    "MarketplaceBrowseHandler": "aragora.server.handlers.marketplace_browse",
    "MetricsHandler": "aragora.server.handlers.metrics",
    "ModerationHandler": "aragora.server.handlers.moderation",
    "ModerationAnalyticsHandler": "aragora.server.handlers.moderation_analytics",
    "MLHandler": "aragora.server.handlers.ml",
    "MomentsHandler": "aragora.server.handlers.moments",
    "OAuthHandler": "aragora.server.handlers.oauth",
    "OAuthWizardHandler": "aragora.server.handlers.oauth_wizard",
    "OpenClawGatewayHandler": "aragora.server.handlers.openclaw_gateway",
    "OrchestrationCanvasHandler": "aragora.server.handlers.orchestration_canvas",
    "OrchestrationHandler": "aragora.server.handlers.orchestration",
    "OrganizationsHandler": "aragora.server.handlers.organizations",
    "PartnerHandler": "aragora.server.handlers.partner",
    "PersonaHandler": "aragora.server.handlers.persona",
    "PlansHandler": "aragora.server.handlers.plans",
    "PlaybookHandler": "aragora.server.handlers.playbooks",
    "PlaygroundHandler": "aragora.server.handlers.playground",
    "PromptEngineHandler": "aragora.server.handlers.prompt_engine",
    "PolicyHandler": "aragora.server.handlers.policy",
    "PrivacyHandler": "aragora.server.handlers.privacy",
    "QueueHandler": "aragora.server.handlers.queue",
    "ReceiptExportHandler": "aragora.server.handlers.receipt_export",
    "ReceiptsHandler": "aragora.server.handlers.receipts",
    "ReplaysHandler": "aragora.server.handlers.replays",
    "RepositoryHandler": "aragora.server.handlers.repository",
    "ReviewsHandler": "aragora.server.handlers.reviews",
    "RLMContextHandler": "aragora.server.handlers.rlm",
    "RoutingHandler": "aragora.server.handlers.routing",
    "SCIMHandler": "aragora.server.handlers.scim_handler",
    "SandboxHandler": "aragora.server.handlers.sandbox",
    "SelectionHandler": "aragora.server.handlers.selection",
    "SkillMarketplaceHandler": "aragora.server.handlers.skill_marketplace",
    "SkillsHandler": "aragora.server.handlers.skills",
    "VisualizationHandler": "aragora.server.handlers.visualization",
    "SLOHandler": "aragora.server.handlers.slo",
    "SMESuccessDashboardHandler": "aragora.server.handlers.sme_success_dashboard",
    "SMEUsageDashboardHandler": "aragora.server.handlers.sme_usage_dashboard",
    "SpendAnalyticsHandler": "aragora.server.handlers.spend_analytics",
    "SSOHandler": "aragora.server.handlers.sso",
    "TemplateDiscoveryHandler": "aragora.server.handlers.template_discovery",
    "TemplateMarketplaceHandler": "aragora.server.handlers.template_marketplace",
    "TemplateRegistryHandler": "aragora.server.handlers.workflows.registry",
    "ThreatIntelHandler": "aragora.server.handlers.threat_intel",
    "TournamentHandler": "aragora.server.handlers.tournaments",
    "TrainingHandler": "aragora.server.handlers.training",
    "TranscriptionHandler": "aragora.server.handlers.transcription",
    "UncertaintyHandler": "aragora.server.handlers.uncertainty",
    "UnifiedMetricsHandler": "aragora.server.handlers.metrics_endpoint",
    "UsageMeteringHandler": "aragora.server.handlers.usage_metering",
    "VerticalsHandler": "aragora.server.handlers.verticals",
    "VoiceHandler": "aragora.server.handlers.voice.handler",
    "WebhookHandler": "aragora.server.handlers.webhooks",
    "WorkflowHandler": "aragora.server.handlers.workflows",
    "WorkspaceHandler": "aragora.server.handlers.workspace",
    # Workflow templates handlers
    "WorkflowTemplatesHandler": "aragora.server.handlers.workflow_templates",
    "WorkflowCategoriesHandler": "aragora.server.handlers.workflow_templates",
    "WorkflowPatternsHandler": "aragora.server.handlers.workflow_templates",
    "WorkflowPatternTemplatesHandler": "aragora.server.handlers.workflow_templates",
    "TemplateRecommendationsHandler": "aragora.server.handlers.workflow_templates",
    "SMEWorkflowsHandler": "aragora.server.handlers.workflow_templates",
    # workflows/ directory
    "WorkflowBuilderHandler": "aragora.server.handlers.workflows.builder",
    # Gauntlet v1 handlers
    "GauntletSchemaHandler": "aragora.server.handlers.gauntlet_v1",
    "GauntletAllSchemasHandler": "aragora.server.handlers.gauntlet_v1",
    "GauntletTemplatesListHandler": "aragora.server.handlers.gauntlet_v1",
    "GauntletTemplateHandler": "aragora.server.handlers.gauntlet_v1",
    "GauntletReceiptExportHandler": "aragora.server.handlers.gauntlet_v1",
    "GauntletHeatmapExportHandler": "aragora.server.handlers.gauntlet_v1",
    "GauntletValidateReceiptHandler": "aragora.server.handlers.gauntlet_v1",
    "GAUNTLET_V1_HANDLERS": "aragora.server.handlers.gauntlet_v1",
    # Cross-pollination handlers
    "CrossPollinationStatsHandler": "aragora.server.handlers.cross_pollination",
    "CrossPollinationSubscribersHandler": "aragora.server.handlers.cross_pollination",
    "CrossPollinationBridgeHandler": "aragora.server.handlers.cross_pollination",
    "CrossPollinationMetricsHandler": "aragora.server.handlers.cross_pollination",
    "CrossPollinationResetHandler": "aragora.server.handlers.cross_pollination",
    "CrossPollinationKMHandler": "aragora.server.handlers.cross_pollination",
    "CrossPollinationKMSyncHandler": "aragora.server.handlers.cross_pollination",
    "CrossPollinationKMStalenessHandler": "aragora.server.handlers.cross_pollination",
    "CrossPollinationKMCultureHandler": "aragora.server.handlers.cross_pollination",
    # Onboarding handlers
    "handle_get_flow": "aragora.server.handlers.onboarding",
    "handle_init_flow": "aragora.server.handlers.onboarding",
    "handle_update_step": "aragora.server.handlers.onboarding",
    "handle_get_templates": "aragora.server.handlers.onboarding",
    "handle_first_debate": "aragora.server.handlers.onboarding",
    "handle_quick_start": "aragora.server.handlers.onboarding",
    "handle_analytics": "aragora.server.handlers.onboarding",
    "get_onboarding_handlers": "aragora.server.handlers.onboarding",
    "OnboardingHandler": "aragora.server.handlers.onboarding",
    # Accounting handlers
    "ARAutomationHandler": "aragora.server.handlers.ar_automation",
    "APAutomationHandler": "aragora.server.handlers.ap_automation",
    # RBAC management
    "RBACHandler": "aragora.server.handlers.rbac",
    # Self-improvement
    "SelfImproveHandler": "aragora.server.handlers.self_improve",
    # Spectate (real-time debate observation)
    "SpectateStreamHandler": "aragora.server.handlers.spectate_ws",
    # Readiness check (SME onboarding)
    "ReadinessCheckHandler": "aragora.server.handlers.readiness_check",
}

# List of all handler class names (in priority order for dispatch)
# More specific handlers should come first
ALL_HANDLER_NAMES: list[str] = [
    "GraphDebatesHandler",
    "MatrixDebatesHandler",
    "CompositeHandler",
    "DebatesHandler",
    "AgentConfigHandler",
    "AgentsHandler",
    "HealthHandler",
    "StatusPageHandler",
    "NomicHandler",
    "DocsHandler",
    "SystemHandler",
    "PulseHandler",
    "AnalyticsHandler",
    "AnalyticsDashboardHandler",
    "AnalyticsMetricsHandler",
    "AnalyticsPerformanceHandler",
    "OutcomeAnalyticsHandler",
    "EndpointAnalyticsHandler",
    "CrossPlatformAnalyticsHandler",
    "MetricsHandler",
    "SLOHandler",
    "CrossPollinationStatsHandler",
    "CrossPollinationSubscribersHandler",
    "CrossPollinationBridgeHandler",
    "CrossPollinationMetricsHandler",
    "CrossPollinationResetHandler",
    "CrossPollinationKMHandler",
    "CrossPollinationKMSyncHandler",
    "CrossPollinationKMStalenessHandler",
    "CrossPollinationKMCultureHandler",
    "ConsensusHandler",
    "BeliefHandler",
    "SkillsHandler",
    "BindingsHandler",
    "DecisionExplainHandler",
    "DecisionHandler",
    "OutcomeHandler",
    "ControlPlaneHandler",
    "DeliberationsHandler",
    "CritiqueHandler",
    "GenesisHandler",
    "ReplaysHandler",
    "TournamentHandler",
    "MemoryHandler",
    "CoordinatorHandler",
    "LeaderboardViewHandler",
    "RelationshipHandler",
    "MomentsHandler",
    "DocumentQueryHandler",
    "DocumentHandler",
    "DocumentBatchHandler",
    "FolderUploadHandler",
    "SmartUploadHandler",
    "CloudStorageHandler",
    "FindingWorkflowHandler",
    "EvidenceEnrichmentHandler",
    "SchedulerHandler",
    "AuditSessionsHandler",
    "VerificationHandler",
    "AuditingHandler",
    "SecurityDebateHandler",
    "DashboardHandler",
    "PersonaHandler",
    "IntrospectionHandler",
    "CalibrationHandler",
    "CheckpointHandler",
    "RoutingHandler",
    "RoutingRulesHandler",
    "MLHandler",
    "RLMContextHandler",
    "RLMHandler",
    "SelectionHandler",
    "EvaluationHandler",
    "EvolutionABTestingHandler",
    "EvolutionHandler",
    "PluginsHandler",
    "AudioHandler",
    "DeviceHandler",
    "TranscriptionHandler",
    "SocialMediaHandler",
    "BroadcastHandler",
    "LaboratoryHandler",
    "ProbesHandler",
    "InsightsHandler",
    "KnowledgeHandler",
    "KnowledgeMoundHandler",
    "KnowledgeChatHandler",
    "KMCheckpointHandler",
    "GalleryHandler",
    "BreakpointsHandler",
    "DebateInterventionHandler",
    "LearningHandler",
    "AuthHandler",
    "BillingHandler",
    "BudgetHandler",
    "UsageMeteringHandler",
    "SMEUsageDashboardHandler",
    "SpendAnalyticsHandler",
    "OrganizationsHandler",
    "OAuthHandler",
    "FeaturesHandler",
    "ConnectorsHandler",
    "TeamsIntegrationHandler",
    "IntegrationsHandler",
    "ExternalIntegrationsHandler",
    "IntegrationManagementHandler",
    "OAuthWizardHandler",
    "GmailIngestHandler",
    "GmailQueryHandler",
    "UnifiedInboxHandler",
    "SharedInboxHandler",
    "EmailWebhooksHandler",
    "MemoryAnalyticsHandler",
    "GauntletSchemaHandler",
    "GauntletAllSchemasHandler",
    "GauntletTemplatesListHandler",
    "GauntletTemplateHandler",
    "GauntletReceiptExportHandler",
    "GauntletHeatmapExportHandler",
    "GauntletValidateReceiptHandler",
    "GauntletHandler",
    "ReviewsHandler",
    "FormalVerificationHandler",
    "SlackHandler",
    "EvidenceHandler",
    "WebhookHandler",
    "CodebaseAuditHandler",
    "AdminHandler",
    "SecurityHandler",
    "PolicyHandler",
    "PrivacyHandler",
    "QueueHandler",
    "RepositoryHandler",
    "UncertaintyHandler",
    "VerticalsHandler",
    "WorkspaceHandler",
    "WorkflowHandler",
    "WorkflowTemplatesHandler",
    "WorkflowCategoriesHandler",
    "WorkflowPatternsHandler",
    "WorkflowPatternTemplatesHandler",
    "TemplateRecommendationsHandler",
    "TemplateMarketplaceHandler",
    "MarketplaceHandler",
    "TrainingHandler",
    "EmailHandler",
    "EmailServicesHandler",
    "DependencyAnalysisHandler",
    "IntelligenceHandler",
    "DiscordHandler",
    "GoogleChatHandler",
    "TeamsHandler",
    "TelegramHandler",
    "WhatsAppHandler",
    "ZoomHandler",
    "ExplainabilityHandler",
    "SCIMHandler",
    "A2AHandler",
    "ApprovalHandler",
    "UnifiedApprovalsHandler",
    "AlertHandler",
    "TriggerHandler",
    "MonitoringHandler",
    "AutonomousLearningHandler",
    "CostDashboardHandler",
    "CostHandler",
    "ExpenseHandler",
    "InvoiceHandler",
    "ARAutomationHandler",
    "APAutomationHandler",
    "ReconciliationHandler",
    "CodeReviewHandler",
    "LegalHandler",
    "DevOpsHandler",
    "AdvertisingHandler",
    "AnalyticsPlatformsHandler",
    "CRMHandler",
    "SupportHandler",
    "EcommerceHandler",
    "ComputerUseHandler",
    "GatewayHandler",
    "OpenClawGatewayHandler",
    "ExternalAgentsHandler",
    "GatewayHealthHandler",
    "GatewayAgentsHandler",
    "GatewayCredentialsHandler",
    "HybridDebateHandler",
    "ERC8004Handler",
    "OnboardingHandler",
    "ReadinessCheckHandler",
    "BackupHandler",
    "GmailLabelsHandler",
    "GmailThreadsHandler",
    "RBACHandler",
    "SelfImproveHandler",
    "SpectateStreamHandler",
    "VoiceHandler",
    "AudienceSuggestionsHandler",
    "CanvasHandler",
    "CanvasPipelineHandler",
    "DAGOperationsHandler",
    "ComplianceHandler",
    "DecisionPipelineHandler",
    "OrchestrationHandler",
    # --- Newly registered handlers ---
    # admin/ sub-handlers
    "CreditsAdminHandler",
    "EmergencyAccessHandler",
    "FeatureFlagAdminHandler",
    "LivenessHandler",
    "ReadinessHandler",
    "StorageHealthHandler",
    # agents/ sub-handlers
    "AgentRecommendationHandler",
    "FeedbackHandler",
    # canvas pipeline stages
    "ActionCanvasHandler",
    "GoalCanvasHandler",
    "IdeaCanvasHandler",
    "OrchestrationCanvasHandler",
    # connectors
    "ConnectorManagementHandler",
    # debates/ sub-handlers
    "PublicDebateViewerHandler",
    "DebateShareHandler",
    "DebateStatsHandler",
    "DecisionPackageHandler",
    # email-related
    "EmailDebateHandler",
    "EmailTriageHandler",
    # features/ sub-handlers
    "AgentDashboardHandler",
    "OutlookHandler",
    # gateway
    "GatewayConfigHandler",
    # github
    "AuditGitHubBridgeHandler",
    "PRReviewHandler",
    # integrations
    "AutomationHandler",
    "IntegrationHealthHandler",
    # knowledge/ sub-handlers
    "KMAdapterStatusHandler",
    "SharingNotificationsHandler",
    # memory/ sub-handlers
    "UnifiedMemoryHandler",
    # notifications
    "NotificationHistoryHandler",
    "NotificationPreferencesHandler",
    # payments
    "PaymentRoutesHandler",
    # pipeline
    "PipelineGraphHandler",
    "PipelineTransitionsHandler",
    "PlanManagementHandler",
    "ProvenanceExplorerHandler",
    "UniversalGraphHandler",
    # sme/ sub-handlers
    "BudgetControlsHandler",
    "ReceiptDeliveryHandler",
    "SlackWorkspaceHandler",
    "TeamsWorkspaceHandler",
    # social/ sub-handlers
    "ChannelHealthHandler",
    "DiscordOAuthHandler",
    "NotificationsHandler",
    "SharingHandler",
    "SlackOAuthHandler",
    "TeamsOAuthHandler",
    # streaming
    "StreamingConnectorHandler",
    # tasks
    "TaskExecutionHandler",
    # top-level handlers
    "AuditTrailHandler",
    "BenchmarkingHandler",
    "DifferentiationHandler",
    "ComplianceReportHandler",
    "ContextBudgetHandler",
    "DRHandler",
    "FeatureFlagsHandler",
    "FeedbackRoutesHandler",
    "GasTownDashboardHandler",
    "GDPRDeletionHandler",
    "MarketplaceBrowseHandler",
    "ModerationHandler",
    "ModerationAnalyticsHandler",
    "PartnerHandler",
    "PlansHandler",
    "PlaybookHandler",
    "PlaygroundHandler",
    "PromptEngineHandler",
    "ReceiptExportHandler",
    "ReceiptsHandler",
    "SkillMarketplaceHandler",
    "SMESuccessDashboardHandler",
    "SMEWorkflowsHandler",
    "SSOHandler",
    "TemplateDiscoveryHandler",
    "TemplateRegistryHandler",
    "ThreatIntelHandler",
    "UnifiedMetricsHandler",
    # workflows/ sub-handlers
    "WorkflowBuilderHandler",
]
