#!/usr/bin/env python3
"""
Compute documentation stats and rewrite generated metrics blocks.

Volatile counts in prose docs live inside delimited blocks:

    <!-- metrics:begin <key> -->
    ...generated content, owned entirely by this script...
    <!-- metrics:end -->

This script rewrites ONLY those blocks (#8792). Values come from
docs/METRICS.md (regenerated by scripts/regenerate_metrics.py) plus the
project version from pyproject.toml. It never edits prose outside the
delimiters, and it fails closed: a block with an unknown key, an
unterminated block, or a missing METRICS.md row aborts the run before
any file is written.

docs-site/ mirrors are excluded: they are owned by
docs-site/scripts/sync-docs.js, which mirrors the source docs (including
CLAUDE.md -> contributing/claude.md) after this script runs.

Usage:
  python scripts/doc_stats.py            # print metrics report only
  python scripts/doc_stats.py --write    # rewrite generated blocks in-place
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path
from collections.abc import Callable


ROOT = Path(__file__).resolve().parents[1]

BLOCK_RE = re.compile(
    r"<!-- metrics:begin (?P<key>[a-z0-9-]+) -->\n(?P<body>.*?)<!-- metrics:end -->",
    re.DOTALL,
)
BLOCK_MARKER = "<!-- metrics:begin"

# Directory names skipped when falling back to a filesystem walk.
_SKIP_DIRS = {
    "docs-site",
    "node_modules",
    ".git",
    ".venv",
    "__pycache__",
    ".worktrees",
    ".claude",
}


@dataclass
class Stats:
    python_modules: int
    test_count: int
    test_files: int
    api_paths: int
    api_operations: int
    ws_event_types: int
    km_adapters_registered: int
    workflow_templates: int
    ts_namespaces: int
    agent_types_allowlisted: int


@dataclass(frozen=True)
class CanonicalMetric:
    value: int
    has_plus: bool


def _metrics_doc_values() -> dict[str, CanonicalMetric]:
    """Read exact generated values from docs/METRICS.md."""
    path = ROOT / "docs" / "METRICS.md"
    if not path.exists():
        return {}

    key_for = {
        "python files under aragora/": "python_files",
        "python lines of code under aragora/": "python_lines",
        "top-level modules under aragora/": "top_level_modules",
        "test files (test_*.py under tests/)": "test_files",
        "test functions (class + module level)": "tests",
        "openapi paths": "api_paths",
        "openapi operations (http verbs)": "api_operations",
        "allowlisted agent types": "allowlisted_agent_types",
        "knowledge mound adapter specs": "adapter_specs",
        "knowledge mound adapter files": "adapter_files",
    }
    metrics: dict[str, CanonicalMetric] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.startswith("|"):
            continue
        cells = [cell.strip().strip("*") for cell in line.strip().strip("|").split("|")]
        if len(cells) < 2:
            continue
        key = key_for.get(cells[0].lower())
        if not key:
            continue
        value_text = cells[1].strip().strip("`")
        num = re.search(r"\d+(?:,\d+)*", value_text)
        if not num:
            continue
        metrics[key] = CanonicalMetric(
            value=int(num.group(0).replace(",", "")),
            has_plus="+" in value_text,
        )
    return metrics


def _canonical_count(canonical: dict[str, CanonicalMetric], key: str, measured: str) -> str:
    metric = canonical.get(key)
    if not metric:
        return measured
    suffix = "+" if metric.has_plus else ""
    return f"{metric.value:,}{suffix}"


def _project_version() -> str:
    """Read the project version from pyproject.toml."""
    path = ROOT / "pyproject.toml"
    if not path.exists():
        return ""
    m = re.search(r'^version\s*=\s*"([^"]+)"', path.read_text(encoding="utf-8"), re.MULTILINE)
    return m.group(1) if m else ""


# ---------------------------------------------------------------------------
# Live-scan counters (CLI report only; never used to rewrite docs)
# ---------------------------------------------------------------------------


def _count_py_files(path: Path) -> int:
    if not path.exists():
        return 0
    return sum(
        1
        for p in path.rglob("*.py")
        if "__pycache__" not in p.parts and ".venv" not in p.parts and "node_modules" not in p.parts
    )


def _count_tests() -> int:
    # Keep the docs baseline stable across platforms and CI environments by
    # counting only tracked test definitions under tests/.
    try:
        out = subprocess.check_output(
            ["git", "grep", "-E", r"^[[:space:]]*(async )?def test_", "--", "tests"],
            cwd=ROOT,
            text=True,
        )
        return len(out.splitlines())
    except (FileNotFoundError, subprocess.CalledProcessError):
        tests_dir = ROOT / "tests"
        if not tests_dir.exists():
            return 0
        pattern = re.compile(r"^\s*(?:async\s+)?def test_", re.MULTILINE)
        total = 0
        for p in tests_dir.rglob("*.py"):
            total += len(pattern.findall(p.read_text(errors="ignore")))
        return total


def _count_test_files() -> int:
    try:
        out = subprocess.check_output(["git", "ls-files", "tests"], cwd=ROOT, text=True)
        return sum(1 for line in out.splitlines() if re.search(r"(^|/)test_[^/]*\.py$", line))
    except (FileNotFoundError, subprocess.CalledProcessError):
        tests_dir = ROOT / "tests"
        if not tests_dir.exists():
            return 0
        return sum(1 for p in tests_dir.rglob("test_*.py") if p.is_file())


def _count_api_ops() -> tuple[int, int]:
    candidates = [
        ROOT / "docs/api/openapi.json",
        ROOT / "docs/api/openapi_generated.json",
        ROOT / "docs/api/openapi.yaml",
    ]
    spec_path = next((p for p in candidates if p.exists()), None)
    if not spec_path:
        return 0, 0
    data: dict
    if spec_path.suffix == ".json":
        data = json.loads(spec_path.read_text())
    else:
        # YAML file may be JSON-formatted; try JSON parse first
        raw = spec_path.read_text()
        try:
            data = json.loads(raw)
        except json.JSONDecodeError:
            return 0, 0
    paths = data.get("paths", {})
    ops = 0
    for _, methods in paths.items():
        for method in methods:
            if method.lower() in {"get", "post", "put", "patch", "delete", "head", "options"}:
                ops += 1
    return len(paths), ops


def _count_ws_events() -> int:
    path = ROOT / "aragora/events/types.py"
    if not path.exists():
        return 0
    text = path.read_text()
    in_enum = False
    count = 0
    for line in text.splitlines():
        if line.startswith("class StreamEventType"):
            in_enum = True
            continue
        if in_enum and line.startswith("class ") and not line.startswith("class StreamEventType"):
            break
        if not in_enum:
            continue
        if re.match(r"\s*[A-Z0-9_]+\s*=\s*\"[a-z0-9_]+\"", line):
            count += 1
    return count


def _count_km_adapters() -> int:
    path = ROOT / "aragora/knowledge/mound/adapters/factory.py"
    if not path.exists():
        return 0
    text = path.read_text()
    return len(re.findall(r'"\.[a-z_]+_adapter"', text))


def _count_templates() -> int:
    base = ROOT / "aragora/workflow/templates"
    if not base.exists():
        return 0
    exts = {".yaml", ".yml", ".py"}
    return sum(
        1
        for p in base.rglob("*")
        if p.is_file() and p.suffix in exts and "__pycache__" not in p.parts
    )


def _count_ts_namespaces() -> int:
    base = ROOT / "sdk/typescript/src/namespaces"
    if not base.exists():
        return 0
    return sum(1 for p in base.glob("*.ts") if p.is_file())


def _count_allowlisted_agents() -> int:
    path = ROOT / "aragora/config/settings.py"
    if not path.exists():
        return 0
    text = path.read_text()
    m = re.search(r"ALLOWED_AGENT_TYPES:.*?=\s*frozenset\((\s*\{.*?\}\s*)\)", text, re.S)
    if not m:
        return 0
    return len(re.findall(r"\"([^\"]+)\"", m.group(1)))


def compute_stats() -> Stats:
    python_modules = _count_py_files(ROOT / "aragora")
    test_count = _count_tests()
    test_files = _count_test_files()
    api_paths, api_operations = _count_api_ops()
    ws_event_types = _count_ws_events()
    km_adapters_registered = _count_km_adapters()
    workflow_templates = _count_templates()
    ts_namespaces = _count_ts_namespaces()
    agent_types_allowlisted = _count_allowlisted_agents()
    return Stats(
        python_modules=python_modules,
        test_count=test_count,
        test_files=test_files,
        api_paths=api_paths,
        api_operations=api_operations,
        ws_event_types=ws_event_types,
        km_adapters_registered=km_adapters_registered,
        workflow_templates=workflow_templates,
        ts_namespaces=ts_namespaces,
        agent_types_allowlisted=agent_types_allowlisted,
    )


# ---------------------------------------------------------------------------
# Generated metrics blocks
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class RenderContext:
    metrics: dict[str, CanonicalMetric]
    version: str

    def exact(self, key: str) -> str:
        return f"{self.metrics[key].value:,}"

    def value(self, key: str) -> int:
        return self.metrics[key].value

    def floored(self, key: str, step: int) -> str:
        return f"{(self.metrics[key].value // step) * step:,}"


def _render_readme_scale(ctx: RenderContext) -> str:
    loc_millions = (ctx.value("python_lines") // 100_000) / 10
    return (
        "> Scale (canonical counts in [`docs/METRICS.md`](docs/METRICS.md), rounded):\n"
        f"> **~{ctx.floored('python_files', 100)} Python files · ~{loc_millions}M LOC · "
        f"{ctx.floored('top_level_modules', 10)}+ top-level modules · "
        f"{ctx.floored('tests', 100_000)}+ test\n"
        f"> functions across ~{ctx.floored('test_files', 100)} files · "
        f"{ctx.exact('api_operations')} API operations across {ctx.exact('api_paths')} paths ·\n"
        f"> {ctx.exact('allowlisted_agent_types')}+ allowlisted agent types across 12+ providers · "
        f"{ctx.exact('adapter_specs')} Knowledge Mound adapter specs\n"
        f"> ({ctx.exact('adapter_files')} files) · 360+ RBAC permissions · "
        f"Python + TypeScript SDKs · v{ctx.version}.**\n"
        "> (Practical real-time debate uses 2–6 agents; the value is *heterogeneity*, not raw\n"
        "> count — see docs/HONEST_ASSESSMENT.md.)"
    )


def _render_extended_readme_scale(ctx: RenderContext) -> str:
    return (
        f"**Scale:** {ctx.exact('python_files')} tracked Python files | "
        f"{ctx.exact('top_level_modules')} top-level modules | "
        f"{ctx.exact('tests')} test functions across {ctx.exact('test_files')} test files | "
        "canonical counts in [METRICS.md](METRICS.md)"
    )


def _render_extended_readme_api_surface(ctx: RenderContext) -> str:
    return (
        f"The server exposes {ctx.exact('api_operations')} API operations across "
        f"{ctx.exact('api_paths')} paths. Key categories:"
    )


def _render_canonical_goals_metrics(ctx: RenderContext) -> str:
    return "\n".join(
        [
            "| Metric | Value | Source |",
            "|--------|-------|--------|",
            f"| Version | {ctx.version} | `pyproject.toml` |",
            f"| Python files under `aragora/` | {ctx.exact('python_files')} | `docs/METRICS.md` |",
            f"| Python modules | {ctx.exact('top_level_modules')} top-level package directories "
            "| `docs/METRICS.md` |",
            f"| Lines of code under `aragora/` | {ctx.exact('python_lines')} | `docs/METRICS.md` |",
            f"| Automated tests | {ctx.exact('tests')} test functions | `docs/METRICS.md` |",
            f"| Test files | {ctx.exact('test_files')} | `docs/METRICS.md` |",
            f"| API operations | {ctx.exact('api_operations')} across {ctx.exact('api_paths')} "
            "paths | `docs/METRICS.md` |",
            f"| API paths | {ctx.exact('api_paths')} | `docs/METRICS.md` |",
            f"| Knowledge Mound adapters | {ctx.exact('adapter_files')} adapter files / "
            f"{ctx.exact('adapter_specs')} registered specs | `docs/METRICS.md` |",
        ]
    )


def _render_status_codebase_metrics(ctx: RenderContext) -> str:
    return "\n".join(
        [
            f"- **Python files (`aragora/`)**: {ctx.exact('python_files')}",
            f"- **Tests**: {ctx.exact('tests')} across {ctx.exact('test_files')} test files",
            f"- **KM adapters**: {ctx.exact('adapter_specs')} registered adapter specs",
            f"- **API operations**: {ctx.exact('api_operations')} across "
            f"{ctx.exact('api_paths')} paths",
        ]
    )


def _render_architecture_scale(ctx: RenderContext) -> str:
    return "\n".join(
        [
            f"- **Test coverage**: {ctx.exact('tests')} tests across "
            f"{ctx.exact('test_files')} test files",
            f"- **Source files**: {ctx.exact('python_files')} Python files under `aragora/`",
            f"- **API surface**: {ctx.exact('api_operations')} API operations across "
            f"{ctx.exact('api_paths')} paths",
            f"- **KM adapters**: {ctx.exact('adapter_specs')} registered adapters "
            "(see `aragora/knowledge/mound/adapters/`)",
        ]
    )


def _render_feature_discovery_total(ctx: RenderContext) -> str:
    return (
        f"**Total**: 230+ features | {ctx.exact('python_files')} Python files | "
        f"{ctx.exact('tests')} tests | {ctx.exact('api_operations')} API operations "
        f"across {ctx.exact('api_paths')} paths"
    )


def _render_km_adapter_specs(ctx: RenderContext) -> str:
    return (
        f"- **{ctx.exact('adapter_specs')} registered adapter specs** wired via "
        "`aragora/knowledge/mound/adapters/factory.py`"
    )


RENDERERS: dict[str, Callable[[RenderContext], str]] = {
    "readme-scale": _render_readme_scale,
    "extended-readme-scale": _render_extended_readme_scale,
    "extended-readme-api-surface": _render_extended_readme_api_surface,
    "canonical-goals-metrics": _render_canonical_goals_metrics,
    "status-codebase-metrics": _render_status_codebase_metrics,
    "architecture-scale": _render_architecture_scale,
    "feature-discovery-total": _render_feature_discovery_total,
    "km-adapter-specs": _render_km_adapter_specs,
}

# Every METRICS.md row any renderer depends on. --write fails closed if one
# is missing so a truncated METRICS.md can never blank out generated claims.
REQUIRED_METRIC_KEYS = frozenset(
    {
        "python_files",
        "python_lines",
        "top_level_modules",
        "tests",
        "test_files",
        "api_paths",
        "api_operations",
        "allowlisted_agent_types",
        "adapter_specs",
        "adapter_files",
    }
)


def _tracked_markdown_files() -> list[Path]:
    """Markdown files that may carry generated blocks (docs-site excluded)."""
    try:
        out = subprocess.check_output(
            ["git", "ls-files", "--", "*.md", ":(exclude)docs-site"],
            cwd=ROOT,
            text=True,
        )
        return [ROOT / line for line in out.splitlines() if line.strip()]
    except (FileNotFoundError, subprocess.CalledProcessError):
        return [
            p for p in ROOT.rglob("*.md") if not (_SKIP_DIRS & set(p.relative_to(ROOT).parts[:-1]))
        ]


def rewrite_metric_blocks(write: bool) -> int:
    """Rewrite all generated metrics blocks. Returns count of changed files.

    Fails closed (RuntimeError, before any write) on: missing METRICS.md rows,
    missing project version, unknown block keys, or malformed delimiters.
    """
    metrics = _metrics_doc_values()
    missing = sorted(REQUIRED_METRIC_KEYS - set(metrics))
    if missing:
        raise RuntimeError(
            "refusing to update generated metrics blocks because docs/METRICS.md "
            "is missing rows: " + ", ".join(missing)
        )
    version = _project_version()
    if not version:
        raise RuntimeError(
            "refusing to update generated metrics blocks: could not read project "
            "version from pyproject.toml"
        )
    ctx = RenderContext(metrics=metrics, version=version)

    # First pass: render everything and fail closed before touching any file.
    pending: list[tuple[Path, str]] = []
    for path in _tracked_markdown_files():
        try:
            original = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        if BLOCK_MARKER not in original:
            continue

        matches = list(BLOCK_RE.finditer(original))
        marker_count = original.count(BLOCK_MARKER)
        if marker_count != len(matches):
            raise RuntimeError(
                f"{path}: found {marker_count} '{BLOCK_MARKER}' marker(s) but only "
                f"{len(matches)} well-formed block(s); check delimiters "
                "(expected '<!-- metrics:begin <key> -->' ... '<!-- metrics:end -->')"
            )
        unknown = sorted({m.group("key") for m in matches} - set(RENDERERS))
        if unknown:
            raise RuntimeError(
                f"{path}: unknown metrics block key(s): {', '.join(unknown)}; "
                "add a renderer to scripts/doc_stats.py or fix the block key"
            )

        def _replace(match: re.Match[str]) -> str:
            key = match.group("key")
            rendered = RENDERERS[key](ctx)
            return f"<!-- metrics:begin {key} -->\n{rendered}\n<!-- metrics:end -->"

        updated = BLOCK_RE.sub(_replace, original)
        if updated != original:
            pending.append((path, updated))

    for path, updated in pending:
        if write:
            path.write_text(updated, encoding="utf-8")
    return len(pending)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--write", action="store_true", help="Rewrite generated metrics blocks in-place"
    )
    args = parser.parse_args()

    stats = compute_stats()
    metrics_doc = _metrics_doc_values()
    print("Live doc stats from repository scan:")
    print(f"- Python modules (aragora/, live scan): {stats.python_modules}")
    print(f"- Tests (def test_ across repo, live scan): {stats.test_count}")
    print(f"- Test files (tests/, live scan): {stats.test_files}")
    print(f"- API paths (docs/api/openapi.json): {stats.api_paths}")
    print(f"- API operations (docs/api/openapi.json): {stats.api_operations}")
    print(f"- WebSocket event types (live scan): {stats.ws_event_types}")
    print(f"- KM adapters registered (live scan): {stats.km_adapters_registered}")
    print(f"- Workflow templates (live scan): {stats.workflow_templates}")
    print(f"- TypeScript namespaces (live scan): {stats.ts_namespaces}")
    print(f"- Allowlisted agent types (settings allowlist): {stats.agent_types_allowlisted}")

    if metrics_doc:
        print("\nExact protected metrics from docs/METRICS.md:")
        print(f"- Python files: {_canonical_count(metrics_doc, 'python_files', 'missing')}")
        print(
            f"- Top-level modules: {_canonical_count(metrics_doc, 'top_level_modules', 'missing')}"
        )
        print(f"- Tests: {_canonical_count(metrics_doc, 'tests', 'missing')}")
        print(f"- Test files: {_canonical_count(metrics_doc, 'test_files', 'missing')}")
        print(f"- API paths: {_canonical_count(metrics_doc, 'api_paths', 'missing')}")
        print(f"- API operations: {_canonical_count(metrics_doc, 'api_operations', 'missing')}")
        print(
            "- Knowledge Mound adapter specs: "
            f"{_canonical_count(metrics_doc, 'adapter_specs', 'missing')}"
        )
        print(
            "- Knowledge Mound adapter files: "
            f"{_canonical_count(metrics_doc, 'adapter_files', 'missing')}"
        )

    if args.write:
        updated = rewrite_metric_blocks(write=True)
        print(f"\nUpdated {updated} documentation files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
