const assert = require('node:assert/strict');
const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { after, test } = require('node:test');

const site = path.resolve(__dirname, '..');
const repo = path.dirname(site);
const sandbox = fs.mkdtempSync(path.join(os.tmpdir(), 'aragora-atlas-sync-'));
after(() => fs.rmSync(sandbox, { recursive: true, force: true }));
fs.mkdirSync(path.join(sandbox, 'docs-site/scripts'), { recursive: true });
fs.symlinkSync(path.join(repo, 'docs'), path.join(sandbox, 'docs'));
for (const name of fs.readdirSync(repo).filter((name) => name.endsWith('.md'))) {
  fs.symlinkSync(path.join(repo, name), path.join(sandbox, name));
}
fs.copyFileSync(
  path.join(__dirname, 'sync-docs.js'),
  path.join(sandbox, 'docs-site/scripts/sync-docs.js'),
);
const output = execFileSync(
  process.execPath,
  [path.join(sandbox, 'docs-site/scripts/sync-docs.js')],
  { encoding: 'utf8' },
);
const pages = { 'README.md': 'overview.md', 'summary.md': 'summary.md' };
const generated = (name) =>
  fs.readFileSync(path.join(sandbox, 'docs-site/docs/reference/atlas', pages[name]), 'utf8');

test('Atlas pages are explicitly mapped under the navigable Reference sidebar', () => {
  const script = fs.readFileSync(path.join(__dirname, 'sync-docs.js'), 'utf8');
  for (const [source, destination] of Object.entries(pages)) {
    assert.ok(script.includes(`'atlas/${source}': 'reference/atlas/${destination}'`));
  }
  const sidebar = require('../sidebars.js').referenceSidebar;
  assert.ok(
    sidebar.some((category) =>
      category.items.some((item) => item.type === 'autogenerated' && item.dirName === 'reference'),
    ),
  );
  const config = fs.readFileSync(path.join(site, 'docusaurus.config.js'), 'utf8');
  assert.match(config, /sidebarId: 'referenceSidebar'/);
});

test('fresh sync has no missing sources and preserves the committed Atlas pages', () => {
  assert.doesNotMatch(output, /Skipping \(not found\)/);
  for (const name of Object.keys(pages)) {
    const source = fs.readFileSync(path.join(repo, 'docs/atlas', name), 'utf8');
    const title = source.match(/^# (.+)$/m)[1];
    assert.ok(generated(name).includes(`# ${title}\n`));
    assert.equal(
      generated(name),
      fs.readFileSync(path.join(site, 'docs/reference/atlas', pages[name]), 'utf8'),
    );
  }
  const tables = (text) => text.split('\n').filter((line) => line.startsWith('|'));
  assert.deepEqual(
    tables(generated('summary.md')),
    tables(fs.readFileSync(path.join(repo, 'docs/atlas/summary.md'), 'utf8')),
  );
  assert.match(generated('summary.md'), /## Pairwise agreement by family pair/);
});

test('Atlas cross-links stay on site and supporting artifacts link to the repository', () => {
  assert.ok(generated('README.md').includes('[`summary.md`](./summary)'));
  assert.ok(generated('summary.md').includes('[README.md](./overview)'));
  const readme = generated('README.md');
  for (const target of [
    'docs/artifacts/2026-07-reviewer-failure-taxonomy.md',
    'docs/atlas/manifest.json',
    'LICENSE',
  ]) {
    assert.ok(readme.includes(`](https://github.com/synaptent/aragora/blob/main/${target})`));
  }
  for (const name of Object.keys(pages)) {
    for (const match of generated(name).matchAll(/\]\(([^)#]+)(?:#[^)]*)?\)/g)) {
      if (/^https?:\/\//.test(match[1])) continue;
      const target = path.resolve(sandbox, 'docs-site/docs/reference/atlas', match[1]);
      assert.ok(
        fs.existsSync(`${target}.md`) || fs.existsSync(path.join(target, 'index.md')),
        `Unresolved Atlas link: ${match[1]}`,
      );
    }
  }
});
