"""
Email HTML formatter for debate results.

Formats debate results as HTML emails with inline CSS,
plus a plain-text fallback.
"""

from __future__ import annotations

from typing import Any

from .debate_formatter import DebateResultFormatter, register_debate_formatter


def _escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#x27;")
    )


def _confidence_color(confidence: float) -> str:
    if confidence >= 0.8:
        return "#22c55e"
    if confidence >= 0.5:
        return "#eab308"
    return "#ef4444"


def _confidence_label(confidence: float) -> str:
    if confidence >= 0.9:
        return "Very High"
    if confidence >= 0.7:
        return "High"
    if confidence >= 0.5:
        return "Moderate"
    return "Low"


@register_debate_formatter("email")
class EmailDebateFormatter(DebateResultFormatter):
    """Format debate results as HTML+plain-text email payloads."""

    def format(
        self,
        result: dict[str, Any],
        options: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Return ``{"html": "...", "text": "..."}``."""
        options = options or {}
        max_answer = options.get("max_answer_length", 500)

        consensus: bool = result.get("consensus_reached", False)
        confidence_raw = result.get("confidence", 0)
        confidence: float = (
            float(confidence_raw) if isinstance(confidence_raw, (int, float)) else 0.0
        )
        rounds = result.get("rounds", result.get("rounds_completed", "N/A"))
        answer = result.get("final_answer", "No conclusion reached.")
        participants = result.get("participants", [])
        duration = result.get("duration_seconds")
        topic = result.get("task", "Debate")

        preview = str(answer)
        if len(preview) > max_answer:
            preview = preview[: max_answer - 3] + "..."

        color = _confidence_color(confidence)
        label = _confidence_label(confidence)
        status = "Yes" if consensus else "No"

        # --- HTML -----------------------------------------------------------
        meta_rows = (
            f'<tr><td style="padding:4px 8px;color:#6b7280;">Consensus</td>'
            f'<td style="padding:4px 8px;">{status}</td></tr>'
            f'<tr><td style="padding:4px 8px;color:#6b7280;">Confidence</td>'
            f'<td style="padding:4px 8px;color:{color};font-weight:bold;">'
            f"{confidence:.0%} ({label})</td></tr>"
            f'<tr><td style="padding:4px 8px;color:#6b7280;">Rounds</td>'
            f'<td style="padding:4px 8px;">{rounds}</td></tr>'
        )
        if participants:
            names = ", ".join(str(p) for p in participants[:5])
            if len(participants) > 5:
                names += f" (+{len(participants) - 5} more)"
            meta_rows += (
                f'<tr><td style="padding:4px 8px;color:#6b7280;">Agents</td>'
                f'<td style="padding:4px 8px;">{_escape_html(names)}</td></tr>'
            )
        if isinstance(duration, (int, float)) and duration > 0:
            meta_rows += (
                f'<tr><td style="padding:4px 8px;color:#6b7280;">Duration</td>'
                f'<td style="padding:4px 8px;">{duration:.1f}s</td></tr>'
            )

        html = (
            "<div style=\"font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',"
            "Roboto,Helvetica,Arial,sans-serif;max-width:600px;margin:0 auto;"
            "padding:20px;background:#fff;border:1px solid #e0e0e0;"
            'border-radius:8px;">'
            '<h1 style="margin:0 0 4px 0;font-size:22px;color:#1f2937;">'
            "Debate Complete</h1>"
            f'<p style="margin:0 0 16px 0;color:#6b7280;font-size:14px;">'
            f"{_escape_html(str(topic)[:200])}</p>"
            '<table style="width:100%;border-collapse:collapse;margin-bottom:16px;">'
            f"{meta_rows}</table>"
            '<hr style="border:none;border-top:1px solid #e5e7eb;margin:16px 0;">'
            '<h2 style="font-size:16px;color:#374151;margin:0 0 8px 0;">Conclusion</h2>'
            f'<p style="color:#1f2937;line-height:1.6;">{_escape_html(preview)}</p>'
            '<p style="text-align:center;color:#9ca3af;font-size:12px;margin-top:20px;'
            'border-top:1px solid #e5e7eb;padding-top:12px;">'
            "Generated by Aragora</p>"
            "</div>"
        )

        # --- Plain text ------------------------------------------------------
        text = self._plain_text(
            result, preview, status, confidence, label, rounds, participants, duration, topic
        )

        return {"html": html, "text": text}

    # ------------------------------------------------------------------

    @staticmethod
    def _plain_text(
        result: dict[str, Any],
        preview: str,
        status: str,
        confidence: float,
        label: str,
        rounds: Any,
        participants: list[Any],
        duration: Any,
        topic: Any,
    ) -> str:
        lines: list[str] = [
            "Debate Complete",
            f"Topic: {str(topic)[:200]}",
            "",
            f"Consensus: {status}",
            f"Confidence: {confidence:.0%} ({label})",
            f"Rounds: {rounds}",
        ]
        if participants:
            lines.append(f"Agents: {len(participants)}")
        if isinstance(duration, (int, float)) and duration > 0:
            lines.append(f"Duration: {duration:.1f}s")
        lines.append("")
        lines.append("Conclusion:")
        lines.append(preview)
        return "\n".join(lines)

    # ------------------------------------------------------------------

    def format_summary(
        self,
        result: dict[str, Any],
        max_length: int = 500,
    ) -> str:
        """Return a compact plain-text summary for email subject lines."""
        consensus = result.get("consensus_reached", False)
        confidence_raw = result.get("confidence", 0)
        confidence = float(confidence_raw) if isinstance(confidence_raw, (int, float)) else 0.0
        answer = result.get("final_answer", "No conclusion reached.")

        status = "Consensus" if consensus else "No consensus"
        summary = f"Debate Complete - {status} ({confidence:.0%}): {answer}"
        if len(summary) > max_length:
            summary = summary[: max_length - 3] + "..."
        return summary
