"""
Microsoft Teams Adaptive Card formatter for debate results.

Formats debate results using Teams' Adaptive Cards v1.5 for rich display.
"""

from __future__ import annotations

from typing import Any

from .debate_formatter import DebateResultFormatter, register_debate_formatter


def _confidence_color(confidence: float) -> str:
    """Map confidence to an Adaptive Card colour keyword."""
    if confidence >= 0.8:
        return "Good"
    if confidence >= 0.5:
        return "Warning"
    return "Attention"


@register_debate_formatter("teams")
class TeamsDebateFormatter(DebateResultFormatter):
    """Format debate results for Microsoft Teams using Adaptive Cards v1.5."""

    def format(
        self,
        result: dict[str, Any],
        options: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Return Adaptive Card v1.5 JSON payload.

        Structure:
        - TextBlock header
        - FactSet for metadata (consensus, confidence, rounds, agents, duration)
        - TextBlock body with the final answer
        """
        options = options or {}
        max_answer = options.get("max_answer_length", 500)

        consensus: bool = result.get("consensus_reached", False)
        confidence_raw = result.get("confidence", 0)
        confidence: float = (
            float(confidence_raw) if isinstance(confidence_raw, (int, float)) else 0.0
        )
        rounds = result.get("rounds", result.get("rounds_completed", "N/A"))
        answer = result.get("final_answer", "No conclusion reached.")
        participants = result.get("participants", [])
        duration = result.get("duration_seconds")

        color = _confidence_color(confidence)

        body: list[dict[str, Any]] = []

        # Header
        consensus_icon = "Consensus Reached" if consensus else "No Consensus"
        body.append(
            {
                "type": "TextBlock",
                "size": "Large",
                "weight": "Bolder",
                "text": f"Debate Complete - {consensus_icon}",
                "color": color,
            }
        )

        # Metadata FactSet
        facts: list[dict[str, str]] = [
            {"title": "Consensus", "value": "Yes" if consensus else "No"},
            {"title": "Confidence", "value": f"{confidence:.0%}"},
            {"title": "Rounds", "value": str(rounds)},
        ]
        if participants:
            facts.append({"title": "Agents", "value": str(len(participants))})
        if isinstance(duration, (int, float)) and duration > 0:
            facts.append({"title": "Duration", "value": f"{duration:.1f}s"})

        body.append({"type": "FactSet", "facts": facts, "spacing": "Medium"})

        # Answer body
        preview = str(answer)
        if len(preview) > max_answer:
            preview = preview[: max_answer - 3] + "..."

        body.append(
            {
                "type": "TextBlock",
                "text": "Conclusion",
                "weight": "Bolder",
                "spacing": "Medium",
            }
        )
        body.append(
            {
                "type": "TextBlock",
                "text": preview,
                "wrap": True,
            }
        )

        # Footer
        body.append(
            {
                "type": "TextBlock",
                "text": "Generated by Aragora",
                "size": "Small",
                "color": "Dark",
                "spacing": "Medium",
            }
        )

        return {
            "type": "AdaptiveCard",
            "$schema": "https://adaptivecards.io/schemas/adaptive-card.json",
            "version": "1.5",
            "body": body,
        }

    def format_summary(
        self,
        result: dict[str, Any],
        max_length: int = 500,
    ) -> str:
        """Return a compact plain-text summary for Teams."""
        consensus = result.get("consensus_reached", False)
        confidence_raw = result.get("confidence", 0)
        confidence = float(confidence_raw) if isinstance(confidence_raw, (int, float)) else 0.0
        answer = result.get("final_answer", "No conclusion reached.")

        status = "Consensus" if consensus else "No consensus"
        summary = f"Debate Complete - {status} ({confidence:.0%}): {answer}"
        if len(summary) > max_length:
            summary = summary[: max_length - 3] + "..."
        return summary
