from __future__ import annotations

from pathlib import Path

import pytest

import scripts.generate_openapi as generate_openapi
from aragora.server.handlers.openapi_decorator import (
    api_endpoint,
    clear_registry,
    get_registered_endpoints,
)


def test_ast_extract_endpoints_cleans_docstrings(tmp_path, monkeypatch) -> None:
    monkeypatch.setattr(generate_openapi, "PROJECT_ROOT", tmp_path)
    handler_path = tmp_path / "example_handler.py"
    handler_path.write_text(
        """
from aragora.server.handlers.openapi_decorator import api_endpoint


class ExampleHandler:
    @api_endpoint(path="/api/example", method="GET", summary="Example")
    def handle(self):
        \"\"\"Example summary.

        Details line.
            Preserved nested indentation.
        \"\"\"
        return None
""".strip()
        + "\n",
        encoding="utf-8",
    )

    endpoints = generate_openapi._ast_extract_endpoints_from_file(handler_path)

    assert len(endpoints) == 1
    assert endpoints[0]["description"] == (
        "Example summary.\n\nDetails line.\n    Preserved nested indentation."
    )


def test_api_endpoint_cleans_docstrings() -> None:
    clear_registry()

    @api_endpoint(path="/api/example", method="GET", summary="Example")
    def handle() -> None:
        """Example summary.

        Details line.
            Preserved nested indentation.
        """

    try:
        endpoints = get_registered_endpoints()
        assert endpoints[-1].description == (
            "Example summary.\n\nDetails line.\n    Preserved nested indentation."
        )
    finally:
        clear_registry()


def test_merge_paths_prefers_metadata_over_autogenerated_placeholders() -> None:
    merged = {
        "/api/v1/decision-analytics/example": {
            "get": {
                "summary": "Autogenerated placeholder (spec pending)",
                "x-autogenerated": True,
            }
        }
    }
    incoming = {
        "/api/v1/decision-analytics/example": {
            "get": {
                "summary": "Rich endpoint metadata",
                "operationId": "handle_example",
            }
        }
    }

    generate_openapi._merge_paths_prefer_metadata(merged, incoming)

    operation = merged["/api/v1/decision-analytics/example"]["get"]
    assert operation["summary"] == "Rich endpoint metadata"
    assert operation["operationId"] == "handle_example"
    assert operation.get("x-autogenerated") is not True


def test_merge_paths_preserves_unrelated_autogenerated_placeholders() -> None:
    merged = {
        "/api/v1/example": {
            "get": {
                "summary": "Autogenerated placeholder (spec pending)",
                "x-autogenerated": True,
            }
        }
    }
    incoming = {
        "/api/v1/example": {
            "get": {
                "summary": "Rich endpoint metadata",
                "operationId": "handle_example",
            }
        }
    }

    generate_openapi._merge_paths_prefer_metadata(merged, incoming)

    operation = merged["/api/v1/example"]["get"]
    assert operation["summary"] == "Autogenerated placeholder (spec pending)"
    assert operation.get("x-autogenerated") is True


def test_route_to_spec_path_converts_wildcards_and_version() -> None:
    assert (
        generate_openapi._route_to_spec_path("/api/v1/rbac/roles/*")
        == "/api/v1/rbac/roles/{role_id}"
    )
    assert generate_openapi._route_to_spec_path("/api/runs") == "/api/v1/runs"
    assert (
        generate_openapi._route_to_spec_path("/api/v1/ideas/*/edges/*")
        == "/api/v1/ideas/{idea_id}/edges/{edge_id}"
    )
    assert (
        generate_openapi._route_to_spec_path("POST /api/v1/canvas/pipeline/run")
        == "/api/v1/canvas/pipeline/run"
    )
    # /api/v2 must not be rewritten to /api/v1
    assert generate_openapi._route_to_spec_path("/api/v2/tasks/*") == "/api/v2/tasks/{task_id}"


def test_handler_routes_supplement_adds_uncovered_routes(monkeypatch) -> None:
    import sys
    import types

    class DummyHandler:
        """Dummy handler for supplement tests."""

        ROUTES = [
            "/api/v1/dummy/things",
            "/api/v1/dummy/things/*",
            "/api/v1/dummy/execute",
            "/api/v1/control-plane/internal-only",
        ]
        POST_ROUTES = ["/api/v1/dummy/submit"]

    fake_registry = types.SimpleNamespace(HANDLER_REGISTRY=[("_dummy", DummyHandler)])
    monkeypatch.setitem(sys.modules, "aragora.server.handler_registry", fake_registry)

    existing = {"/api/v1/dummy/things": {"get": {"summary": "documented"}}}
    supplement = generate_openapi._collect_handler_routes_supplement(existing)

    # Covered path is skipped; wildcard becomes a named param
    assert "/api/v1/dummy/things" not in supplement
    assert "/api/v1/dummy/things/{thing_id}" in supplement
    # Internal prefix families are never published
    assert not any(p.startswith("/api/v1/control-plane/") for p in supplement)
    # Action-verb segment infers POST; plain segments infer GET
    assert "post" in supplement["/api/v1/dummy/execute"]
    assert supplement["/api/v1/dummy/execute"]["post"]["x-method-inferred"] is True
    # Method-specific *_ROUTES carry their declared method
    assert "post" in supplement["/api/v1/dummy/submit"]
    assert supplement["/api/v1/dummy/submit"]["post"]["x-method-inferred"] is False
    # Every supplement operation is marked autogenerated + experimental
    for methods in supplement.values():
        for op in methods.values():
            assert op["x-autogenerated"] is True
            assert op["x-aragora-stability"] == "experimental"


def test_handler_routes_supplement_merges_multiple_methods(monkeypatch) -> None:
    import sys
    import types

    class DummyHandler:
        GET_ROUTES = ["/api/v1/dummy/item"]
        DELETE_ROUTES = ["/api/v1/dummy/item"]

    fake_registry = types.SimpleNamespace(HANDLER_REGISTRY=[("_dummy", DummyHandler)])
    monkeypatch.setitem(sys.modules, "aragora.server.handler_registry", fake_registry)

    supplement = generate_openapi._collect_handler_routes_supplement({})

    assert set(supplement["/api/v1/dummy/item"]) == {"get", "delete"}


def test_handler_routes_supplement_fails_closed_without_route_policy(
    monkeypatch, tmp_path: Path
) -> None:
    import sys
    import types

    class DummyHandler:
        ROUTES = ["/api/v1/dummy/things"]

    fake_registry = types.SimpleNamespace(HANDLER_REGISTRY=[("_dummy", DummyHandler)])
    monkeypatch.setitem(sys.modules, "aragora.server.handler_registry", fake_registry)
    # No scripts/baselines/internal_route_prefixes.json under tmp_path.
    monkeypatch.setattr(generate_openapi, "PROJECT_ROOT", tmp_path)

    with pytest.raises(SystemExit) as excinfo:
        generate_openapi._collect_handler_routes_supplement({})
    assert "internal_route_prefixes.json" in str(excinfo.value)


def test_handler_routes_supplement_fails_closed_on_unparseable_policy(
    monkeypatch, tmp_path: Path
) -> None:
    import sys
    import types

    class DummyHandler:
        ROUTES = ["/api/v1/dummy/things"]

    fake_registry = types.SimpleNamespace(HANDLER_REGISTRY=[("_dummy", DummyHandler)])
    monkeypatch.setitem(sys.modules, "aragora.server.handler_registry", fake_registry)
    policy = tmp_path / "scripts" / "baselines" / "internal_route_prefixes.json"
    policy.parent.mkdir(parents=True)
    policy.write_text("{not json", encoding="utf-8")
    monkeypatch.setattr(generate_openapi, "PROJECT_ROOT", tmp_path)

    with pytest.raises(SystemExit) as excinfo:
        generate_openapi._collect_handler_routes_supplement({})
    assert "internal_route_prefixes.json" in str(excinfo.value)


def test_handler_routes_supplement_derives_verbs_from_handler_methods(monkeypatch) -> None:
    import sys
    import types

    class MultiVerbHandler:
        """Handler implementing both GET and POST for the same route."""

        ROUTES = ["/api/v1/dummy/multiverb"]

        def handle(self, path, query_params, handler):
            return None

        def handle_post(self, path, query_params, handler):
            return None

    fake_registry = types.SimpleNamespace(HANDLER_REGISTRY=[("_dummy", MultiVerbHandler)])
    monkeypatch.setitem(sys.modules, "aragora.server.handler_registry", fake_registry)

    supplement = generate_openapi._collect_handler_routes_supplement({})

    assert set(supplement["/api/v1/dummy/multiverb"]) == {"get", "post"}
    assert "requestBody" in supplement["/api/v1/dummy/multiverb"]["post"]
    assert "requestBody" not in supplement["/api/v1/dummy/multiverb"]["get"]


def test_handler_routes_supplement_bounds_verb_derivation_to_single_route(monkeypatch) -> None:
    """A multi-route handler must NOT get its class-level verb union per path.

    SandboxHandler-style: the class overrides handle/handle_post/handle_put/
    handle_delete, but each verb belongs to a different ROUTES path. Applying
    the full set to every path would advertise nonexistent operations, so
    multi-route handlers fall back to the per-path segment heuristic.
    """
    import sys
    import types

    class SandboxStyleHandler:
        ROUTES = [
            "/api/v1/sandbox-style/execute",
            "/api/v1/sandbox-style/config",
            "/api/v1/sandbox-style/pool/status",
        ]

        def handle(self, path, query_params, handler):
            return None

        def handle_post(self, path, query_params, handler):
            return None

        def handle_put(self, path, query_params, handler):
            return None

        def handle_delete(self, path, query_params, handler):
            return None

    fake_registry = types.SimpleNamespace(HANDLER_REGISTRY=[("_dummy", SandboxStyleHandler)])
    monkeypatch.setitem(sys.modules, "aragora.server.handler_registry", fake_registry)

    supplement = generate_openapi._collect_handler_routes_supplement({})

    # Per-path heuristic, not the class verb union {get,post,put,delete}
    assert set(supplement["/api/v1/sandbox-style/execute"]) == {"post"}
    assert set(supplement["/api/v1/sandbox-style/config"]) == {"get"}
    assert set(supplement["/api/v1/sandbox-style/pool/status"]) == {"get"}


def test_handler_routes_supplement_no_verb_union_for_lone_uncovered_route(monkeypatch) -> None:
    """Class verbs must be bounded by ALL declared generic routes, not just uncovered ones.

    EmailWebhookHandler-style regression (PR #9332 P2 dissent): the handler
    declares several generic ROUTES; all but one are already covered by the
    spec. The lone uncovered route must NOT inherit the class verb union
    (GET from handle() serving /status + POST from handle_post() serving the
    webhook) — it falls back to the per-path segment heuristic instead.
    """
    import sys
    import types

    class EmailStyleHandler:
        ROUTES = [
            "/api/v1/email-style/status",
            "/api/v1/email-style/webhook/mailgun",
        ]

        def handle(self, path, query_params, handler):
            return None  # serves GET /status only

        def handle_post(self, path, query_params, handler):
            return None  # serves POST /webhook/mailgun only

    fake_registry = types.SimpleNamespace(HANDLER_REGISTRY=[("_dummy", EmailStyleHandler)])
    monkeypatch.setitem(sys.modules, "aragora.server.handler_registry", fake_registry)

    existing = {"/api/v1/email-style/status": {"get": {"summary": "documented"}}}
    supplement = generate_openapi._collect_handler_routes_supplement(existing)

    # Segment heuristic (mailgun -> POST), never the class union {get, post}:
    # GET /webhook/mailgun would 404 at runtime (handle() ignores that path).
    assert set(supplement["/api/v1/email-style/webhook/mailgun"]) == {"post"}


def test_filter_internal_paths_drops_internal_families_from_any_tier() -> None:
    """The internal-route policy applies to the final path set, every tier.

    PR #9332 P2 dissent regression: Tier-1/2/3 outputs (canonical registry,
    @api_endpoint decorators, AST scan) bypassed the policy, publishing
    /api/control-plane/* and /api/v1/sme/* into the public spec — invisible
    to the route-coverage gate, which excludes internal prefixes from both
    sides of its comparison.
    """
    paths = {
        "/api/v1/debates": {"get": {"summary": "public"}},
        "/api/v1/control-plane/audit": {"get": {"summary": "internal"}},
        # Unversioned form must be caught via comparison-key normalization
        # (/api/ -> /api/v1/), exactly as dispatch and the gate normalize it.
        "/api/control-plane/queue/metrics": {"get": {"summary": "internal"}},
        "/api/v1/sme/onboarding": {"post": {"summary": "internal"}},
        "/api/v1/admin/emergency/lockdown": {"post": {"summary": "internal"}},
    }

    filtered = generate_openapi._filter_internal_paths(paths)

    assert set(filtered) == {"/api/v1/debates"}


def test_handler_routes_supplement_uses_explicit_routes_method_verbs(monkeypatch) -> None:
    """Explicit routes() declarations beat verb inference (P2 on #9360).

    Dispatch-based handlers like SSOHandler declare served verbs only via a
    routes() method returning (METHOD, path, name) tuples; their static
    ROUTES list is method-less. Without reading routes(), POST login/callback
    operations were documented as GET-only.
    """
    import sys
    import types

    class DummySSOHandler:
        """Dummy SSO-style handler declaring verbs via routes()."""

        ROUTES = [
            "/api/v1/dummy-sso/login",
            "/api/v1/dummy-sso/status",
        ]

        def __init__(self) -> None:
            raise AssertionError("spec generation must not construct handlers")

        def routes(self) -> list[tuple[str, str, str]]:
            return [
                ("GET", "/api/v1/dummy-sso/login", "handle_login"),
                ("POST", "/api/v1/dummy-sso/login", "handle_login"),
                ("GET", "/api/v1/dummy-sso/status", "handle_status"),
            ]

    fake_registry = types.SimpleNamespace(HANDLER_REGISTRY=[("_dummy_sso", DummySSOHandler)])
    monkeypatch.setitem(sys.modules, "aragora.server.handler_registry", fake_registry)

    supplement = generate_openapi._collect_handler_routes_supplement({})

    login = supplement["/api/v1/dummy-sso/login"]
    assert set(login) == {"get", "post"}
    assert login["post"]["x-method-inferred"] is False
    status = supplement["/api/v1/dummy-sso/status"]
    assert set(status) == {"get"}

    # The real #9360 failure mode: an earlier tier already documented GET,
    # so the generic-ROUTES covered-path skip swallowed the declared POST.
    existing = {"/api/v1/dummy-sso/login": {"get": {"summary": "documented"}}}
    supplement = generate_openapi._collect_handler_routes_supplement(existing)

    login = supplement["/api/v1/dummy-sso/login"]
    assert set(login) == {"post"}
    assert login["post"]["x-method-inferred"] is False


def test_generate_schema_legacy_mode_filters_internal_paths(monkeypatch) -> None:
    """--legacy-handlers output passes through the internal-route policy too.

    The legacy handler-ROUTES generation mode is user-invokable and must not
    become a side door that publishes internal route families the main
    pipeline excludes.
    """
    legacy = {
        "openapi": "3.1.0",
        "paths": {
            "/api/v1/debates": {"get": {"summary": "public"}},
            "/api/v1/control-plane/audit": {"get": {"summary": "internal"}},
        },
    }
    monkeypatch.setattr(generate_openapi, "_legacy_generate_openapi_schema", lambda: legacy)

    schema = generate_openapi.generate_schema(legacy_handlers=True)

    assert "/api/v1/debates" in schema["paths"]
    assert "/api/v1/control-plane/audit" not in schema["paths"]


def test_filter_internal_paths_fails_closed_without_policy(monkeypatch, tmp_path: Path) -> None:
    monkeypatch.setattr(generate_openapi, "PROJECT_ROOT", tmp_path)

    with pytest.raises(SystemExit) as excinfo:
        generate_openapi._filter_internal_paths({"/api/v1/debates": {}})
    assert "internal_route_prefixes.json" in str(excinfo.value)


def test_implemented_handler_verbs_ignores_base_no_op_defaults() -> None:
    from aragora.server.handlers.autonomous.improve import AutonomousImproveHandler
    from aragora.server.handlers.base import BaseHandler

    # Base handler defaults are no-ops and must not count as implementations.
    assert generate_openapi._implemented_handler_verbs(BaseHandler) == []
    # The motivating example: /api/autonomous/improve serves GET and POST.
    assert generate_openapi._implemented_handler_verbs(AutonomousImproveHandler) == [
        "get",
        "post",
    ]


def test_handler_routes_supplement_adds_missing_method_on_covered_path(monkeypatch) -> None:
    """Round-1 review P2 on #9360: a path already documented for one method
    must still receive supplements for OTHER declared methods, targeted at the
    exact existing spec path string so they merge into its path item."""
    import sys
    import types

    class DummyHandler:
        POST_ROUTES = ["/api/v1/dummy/things"]
        DELETE_ROUTES = ["/api/v1/dummy/things/*"]

    fake_registry = types.SimpleNamespace(HANDLER_REGISTRY=[("_dummy", DummyHandler)])
    monkeypatch.setitem(sys.modules, "aragora.server.handler_registry", fake_registry)

    existing = {
        "/api/v1/dummy/things": {"get": {"summary": "documented"}},
        "/api/v1/dummy/things/{thing_id}": {"get": {"summary": "documented"}},
    }
    supplement = generate_openapi._collect_handler_routes_supplement(existing)

    # Undocumented POST on a GET-documented path is supplemented...
    assert "post" in supplement["/api/v1/dummy/things"]
    # ...without re-emitting the documented GET.
    assert "get" not in supplement["/api/v1/dummy/things"]
    # Wildcard route resolves to the EXISTING spec path string (named param),
    # not a parallel {param} duplicate.
    assert "delete" in supplement["/api/v1/dummy/things/{thing_id}"]
    assert not any("{param}" in p for p in supplement)


def test_handler_routes_supplement_skips_method_already_documented(monkeypatch) -> None:
    """A method-declared route whose method IS documented adds nothing."""
    import sys
    import types

    class DummyHandler:
        GET_ROUTES = ["/api/v1/dummy/things"]

    fake_registry = types.SimpleNamespace(HANDLER_REGISTRY=[("_dummy", DummyHandler)])
    monkeypatch.setitem(sys.modules, "aragora.server.handler_registry", fake_registry)

    existing = {"/api/v1/dummy/things": {"get": {"summary": "documented"}}}
    supplement = generate_openapi._collect_handler_routes_supplement(existing)
    assert supplement == {}


def test_merge_supplement_adds_methods_without_overwriting(monkeypatch) -> None:
    """Supplement ops merge method-wise into existing path items: documented
    operations are never overwritten, and same-path supplements land beside
    them instead of being dropped by a path-level setdefault."""
    merged = {"/api/v1/dummy/things": {"get": {"summary": "documented"}}}
    supplement = {
        "/api/v1/dummy/things": {"post": {"summary": "auto"}},
        "/api/v1/dummy/new": {"get": {"summary": "auto"}},
    }
    generate_openapi._merge_supplement(merged, supplement)
    assert merged["/api/v1/dummy/things"]["get"] == {"summary": "documented"}
    assert merged["/api/v1/dummy/things"]["post"] == {"summary": "auto"}
    assert merged["/api/v1/dummy/new"]["get"] == {"summary": "auto"}
